### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by cheelahim** [dotmailer/dotmailer-magento2-extension#1]
Hey @cdiacon !
I appreciate your intentions to follow the semver.
It would be great if you put more efforts to keep the module version in the composer.json synced with git tags. Now you have 1.1.2 version tagged as v1.1.3 which is confusing.
Also, could you please set up a proper hook to keep [packagist](https://packagist.org/about) updated upon new version release.

**Comment by cdiacon** [comment]
@cheelahim thanks for pointing this out.
We know about this and it's a conflict using a mixed semantic version tags 1.1.2 and v1.1.3 and packagist fails to update. 
Both points to the same version so you can use any of these(v1.1.3 if you point direct to github).

Should be fine on any new versions that's coming up.
