### ISSUE TITLE
Can't save customer subscriptions and can't synchronize customers

### ISSUE THREAD

**Issue by al-alieksieienko** [dotmailer/dotmailer-magento2-extension#116]
**1. Magento2.1.1 CE/EE: Exception occurred while trying to save info in MyAccount/Newsletter subscription**

Steps to reproduce:
- Go to BackOffice -> Stores -> Configuration -> Dotmailer -> Configuration -> Customer Addressbook Preference
- Show Datafields To Customer? -> Yes
- Select all available attributes
- Save and flush caches
- Go to Frontend: My account -> Newsletter Subscriptions -> Newsletter Preferences -> Press "Save" button 

_Exception:_
Notice: Undefined index: FIRSTNAME in /home/ISM-ECOMPANY/al.alekseenko/localhost/m2ce-bp-ua-php1/vendor/dotmailer/dotmailer-magento2-extension/Controller/Customer/Newsletter.php on line 143 ....

**2. Magento2.1.1 EE: can`t synchronize customers, exception occurred**
Steps to reproduce:
- register new customer within Magento;
- Go to BackOffice -> Stores -> Configuration -> Dotmailer -> Developer ->Sync settings -> Manually Run Sync -> Contact Sync ->Run now

_Exception:_
Exception #0 (Zend_Db_Statement_Exception): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'pei.entity_id' in 'on clause', query was: SELECT `e`.*, CONCAT(IF(e.prefix IS NOT NULL AND e.prefix != '', CONCAT(LTRIM(RTRIM(e.prefix)), ' '), ''), LTRIM(RTRIM(e.firstname)), ' ', IF(e.middlename IS NOT NULL AND e.middlename != '', CONCAT(LTRIM(RTRIM(e.middlename)), ' ')..................

**Comment by cdiacon** [comment]
@al-alieksieienko thanks for sending this. 
1. Should be fixed and will be released soon in a new version.

2. Regarding the most_brand, can you share the table columns for "catalog_product_entity_int" ?

**Comment by cdiacon** [comment]
Assuming you are using Catalog Staging the columns may be different with the key renamed from entity_id to row_id, can you confirm that?

**Comment by cdiacon** [comment]
Also can you have a look at this existing issue and see if it's related https://github.com/magento/magento2/issues/6478 ?

**Comment by al-alieksieienko** [comment]
I've installed default M2.1.1 EE (clean) and found that yes: Catalog Staging is used by default.
Also I can confirm that this case is related to [magento/magento2#6478](https://github.com/magento/magento2/issues/6478) but solution didn't help me (just to switch reindex modes).
 So I can see only the case for now: install M2.1.1 EE with Catalog Staging disabled (with related modules).

**Comment by cdiacon** [comment]
@al-alieksieienko v2.1.3 should fix the problem. Let me know if you have any issues.
