### ISSUE TITLE
importexport files in the var/ folder

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#12]
We have found an issue with the dotmailer extension that is causing it to flood the Magento /var directory with numerous "importexport" files.

[cid:4A686C52-AF2D-45D1-AAD5-9E38450B4246]

Apparently, the Dotmailer extension /app/code/Dotdigitalgroup/Email/Model/Cron.php uses "Magento\ImportExport\Model\Export\Adapter\Csv" and includes it in it's constructor.

The file Magento\ImportExport\Model\Export\Adapter\Csv constructor calls the parent constructor. The parent class is Magento\ImportExport\Model\Export\Adapter\AbstractAdapter which has this in it's constructor:

public function __construct( 
\Magento\Framework\Filesystem $filesystem, 
$destination = null, 
$destinationDirectoryCode = DirectoryList::VAR_DIR 
) { 
$this->_directoryHandle = $filesystem->getDirectoryWrite($destinationDirectoryCode); 
if (!$destination) { 
$destination = uniqid('importexport_'); 
$this->_directoryHandle->touch($destination); 
} 
... 
}

So just by instantiating this class, an "importexport" file gets created.

There are 3 dotmailer cron jobs that instantiate this file:

* ddg_automation_importer (runs on admin configurable schedule) 
* ddg_automation_abandoncarts (runs every 5 minutes) 
* ddg_automation_campaign (runs every 5 minutes)

This should be fixable by using a proxy object instead of the CSV class, as explained in http://alanstorm.com/magento_2_object_manager_proxy_objects

**Comment by cheelahim** [comment]
Hey @cdiacon,
Using Proxy could prevent Cron from spamming the var directory. Simply add this to di.xml

```xml
 <type name="Dotdigitalgroup\Email\Model\Cron">
    <arguments>
        <argument name="csv" xsi:type="object">Magento\ImportExport\Model\Export\Adapter\Csv\Proxy</argument>
    </arguments>
</type>
```
But why do you need the csv adapter there at all? I couldn't find any Cron::export() calls. 
https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Model/Cron.php#L116
Can you show the case this csv adapter will be invoked, please?

**Comment by cdiacon** [comment]
tnx @cheelahim this method is not needed anymore.
