### ISSUE TITLE
Admin module Configuration can't be saved on M V2.1.2

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#161]
On Magento version v2.1.2 the dynamic content style preview breaks and the configuration settings can't be saved.

![screen shot 2016-12-06 at 10 33 39](https://cloud.githubusercontent.com/assets/728734/20922360/c688f090-bb9f-11e6-8b3f-68ea39e90fe4.png)

**Comment by cdiacon** [comment]
@adeelq you may check this line https://github.com/dotmailer/dotmailer-magento2-extension/blob/1341e82873c268c352e8876bb90dbf2f86c37d9b/view/adminhtml/templates/system/preview.phtml#L80-L80

**Comment by adeelq** [comment]
@cdiacon any error in console

**Comment by adeelq** [comment]
@cdiacon working fine on my local. can you clear generation folder and then check it again

**Comment by cdiacon** [comment]
@adeelq you are missing $j check lines 80 and 90.
