### ISSUE TITLE
Issues with DI in production mode

### ISSUE THREAD

**Issue by vkalchenko** [dotmailer/dotmailer-magento2-extension#162]
Hi.
There are two different errors with wrong variable type:
1. During cron job "ddg_automation_reviews_and_wishlist" running. 
Recoverable Error: Object of class Magento\Framework\ObjectManager\ObjectManager could not be converted to string in /data/www/html/www.familyvideo.com/htdocs/vendor/magento/zendframework1/library/Zend/Date.php on line 156
2. In exception log
report.CRITICAL: Zend_Mail_Transport_Exception: Parameters were set but are not a string in /data/www/html/www.familyvideo.com/htdocs/vendor/magento/zendframework1/library/Zend/Mail/Transport/Sendmail.php:117

Both have the same reason. When Magento 2 is working in production mode - Object Manager works in a different way (in comparison to default and developer modes). If some object has default value of constructor parameter equal to null AND this parameter is not specified in di.xml - Object Manages is passing itself, instead of null.

These errors can be reproduced on dotmailer v2.1.4

To fix this - you need to forcibly specify "null" parameters for such classes, using virtual types. In my pull request, which you closed https://github.com/dotmailer/dotmailer-magento2-extension/pull/158 I added virtual type for Zend_Date in Dotdigitalgroup\Email\Model\Sales\Order. You closed it and said that Zend_Date is removed from constructor. This is not true - Zend_Date is still injected to Dotdigitalgroup\Email\Model\Sales\Order and to Dotdigitalgroup\Email\Helper\Recommend

Also, Zend_Mail_Transport_Sendmail is injected to Dotdigitalgroup\Email\Model\Mail\Transport

You need to review all places, where Zend classes are injected and add virtual types for all classes, which have "null" in constructor.

**Comment by cdiacon** [comment]
@adeelq can you revert this change https://github.com/dotmailer/dotmailer-magento2-extension/commit/6744855d5cc1e058fd299bba139ad509a9cdafe1

we should not use Zend_Date into constructor.

**Comment by vkalchenko** [comment]
@cdiacon What about Dotdigitalgroup\Email\Model\Mail\Transport ? 
It uses Zend_Mail_Transport_Sendmail which also has null in constructor. Why don't you want to use virtual types? In my own extension I use Zend_Http_Client, and I just specified virtual type for it. Everything is working correctly in "production" mode.

**Comment by vkalchenko** [comment]
Hi @cdiacon 
Zend_Mail_Transport_Sendmail should be also set up via virtual type. Right now, in production mode, if I disable transactional emails through Dotmailer - it will completely break down default Magento transactional emails, due to incorrect Zend_Mail_Transport_Sendmail usage.

**Comment by cdiacon** [comment]
@adeelq ^^^
