### ISSUE TITLE
Error on cron job ddg_automation_importer

### ISSUE THREAD

**Issue by vkalchenko** [dotmailer/dotmailer-magento2-extension#163]
Hi. 
There's an error in cron_schedule table for "ddg_automation_importer" job:
Notice: unserialize(): Error at offset 16777211 of 16777215 bytes in /data/www/html/www.familyvideo.com/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Model/Sync/Td/Bulk.php on line 19

Line is - $importData = unserialize($item->getImportData());

On our project $item->getImportData() returns about 16 MB serialized string containing full Magento cache. Looks like issue is related to data size

**Comment by adeelq** [comment]
@vkalchenko can you please give me some more information on the $item. best if you can give me $item data without import_data

**Comment by adeelq** [comment]
@vkalchenko this seems like a support issue please contact support where this will be investigated by support specialist
