### ISSUE TITLE
Existing subscribers are being enrolled when placing an order.

### ISSUE THREAD

**Issue by dotZygis** [dotmailer/dotmailer-magento2-extension#177]
Scenario:

- Subscribe to a newsletter with new subscriber enrollment set as disabled.
- Enable new subscriber enrollment.
- Place an order with that account.

Result: You are enrolled into a program.

This is not the case with guests. Only customers.

**Comment by adeelq** [comment]
@dotZygis I do not think this is a bug. We will evaluate this and most likely this enhancement to feature.

**Comment by adeelq** [comment]
Closing since most likely already fixed in latest release. If not need to create internal issue.
