### ISSUE TITLE
updated contact's last quote id before sending campaign

### ISSUE THREAD

**Issue by adeelq** [dotmailer/dotmailer-magento2-extension#181]
updated contact's last quote id before sending campaign instead of updating when creating AC record in campaigns table. This will resolve the issue where multiple websites are connected to same account and there are two AC emails for same customer for multiple websites.

**Comment by cdiacon** [comment]
This __updated contact's last quote id before sending campaign #181__ is not best solution.

**Comment by adeelq** [comment]
code reverted since not enough time to update quote id before sending campaign
https://github.com/dotmailer/dotmailer-magento2-extension/pull/184/commits/bba74251b419bf00baba478c97444796ae1f27e8
