### ISSUE TITLE
Guest finding

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#187]
Guest order data most of the time remains behind the contacts sync, this ends with missing TD for guest contacts in account.

Need to import the contact fist(non historical) so the order data can ba attached to this contact.

**Comment by adeelq** [comment]
@cdiacon I cannot replicate this i gone through the code and all indication is that importer will priorities contacts over order.

However i was able to think if this scenario where order sync is batched and pushed to queue in importer https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Model/Sync/Order.php#L147

Then a sec after we create guest contact in contacts table https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Model/Sync/Order.php#L193

So while we are waiting for next contact sync to run importer might already be running and trying to process the order sync. Hence failing.

**Comment by cdiacon** [comment]
@adeelq it's not the importer, it's the crontask for orders that runs before the contact. The guest order should be delayed before creating the import to proccess the contact/guest first.

**Comment by adeelq** [comment]
Thanks for your input @cdiacon I'm thinking similar. Working on solution now

**Comment by adeelq** [comment]
@cdiacon so i think this is a good solution where we move out the guest finding and creating process out of order sync and do it in contact sync.

**Comment by TrGlen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bulk guest sync - M2](https://trello.com/c/La04fMnJ/635-bulk-guest-sync-m2)
