### ISSUE TITLE
Abandoned carts time issue

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#189]
Abandoned carts timezone scope is not passing the time so in return gets only the date : 

File Sales/Quote.php

https://github.com/dotmailer/dotmailer-magento2-extension/blob/a4d0730c4714aa2f51681f3b8d48c997f59a2958/Model/Sales/Quote.php#L146-L146

change to : 
```
$fromTime = $this->timeZone->scopeDate($storeId, 'now',true );
````

**Comment by cdiacon** [comment]
@adeelq there is one more issue with timezone for the locale : 

On multiple websites with different locale 
- you should convert the time to UTC before getting the fromtime.

**Comment by adeelq** [comment]
@cdiacon this will get time time from the provided stores timezone. Should be enough. 

    $fromTime = $this->timeZone->scopeDate($storeId, 'now', true);
