### ISSUE TITLE
Easy email capture not updating is_guest field

### ISSUE THREAD

**Issue by dotZygis** [dotmailer/dotmailer-magento2-extension#190]
Not related to emailcapture all the guest imported to the email_contact should be marked is_guest

on this line

https://github.com/dotmailer/dotmailer-magento2-extension/blob/042e3563a216348ce2baf13798ce37aad05be879/Model/Sync/Order.php#L193-L193

**Comment by adeelq** [comment]
@dotZygis not a bug
