### ISSUE TITLE
Get rid of unserialize

### ISSUE THREAD

**Issue by adeelq** [dotmailer/dotmailer-magento2-extension#191]
Magento 2.2 will get rid of unserialize. Switch to json_decode.
https://twitter.com/piotrekkaminski/status/822559850878173184

**Comment by cdiacon** [comment]
@adeelq So next release will include this change 
https://github.com/magento/magento2/commit/2a4e809ff8179d8bcf98783c2d51503102871b65

which means that the serialized values will differ by default.
