### ISSUE TITLE
Abandoned cart with wrong email_contact_id

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#202]
Guest Subscriber sync datafields will populate the wrong email_contact_id for the contacts which is used to send abandoned carts. This will be used to send abandoned carts which don't exist in account : 

https://github.com/dotmailer/dotmailer-magento2-extension/blob/e3544b4e5b9e81457ddb531a9b38aa905af13d58/Model/Newsletter/Subscriber.php#L366-L366

https://github.com/dotmailer/dotmailer-magento2-extension/blob/8646173a57565be6c20ee948830f5335ac147d85/Model/ResourceModel/Contact.php#L168-L168

Will result in error messages like : 

```
One or more of the supplied contacts were not found. Send not permitted. ERROR_CONTACT_NOT_FOUND
```

```
contact id returned is not numeric for email 
```

**Comment by adeelq** [comment]
@cdiacon i dont think i get it. 

https://github.com/dotmailer/dotmailer-magento2-extension/blob/e3544b4e5b9e81457ddb531a9b38aa905af13d58/Model/Newsletter/Subscriber.php#L366-L366

https://github.com/dotmailer/dotmailer-magento2-extension/blob/8646173a57565be6c20ee948830f5335ac147d85/Model/ResourceModel/Contact.php#L168-L168

do not update email_contact_id. They update imported = 1 given in the provided ids.

**Comment by cdiacon** [comment]
This is the key for the contact table "email_contact_id" it's not the contact_id from account also can't replicate and  log  empty responses for now - closing down
