### ISSUE TITLE
Update contacts with customers that are subscribers

### ISSUE THREAD

**Issue by adeelq** [dotmailer/dotmailer-magento2-extension#216]
see https://github.com/dotmailer/dotmailer-magento-extension/issues/220

**Comment by mcspronko** [comment]
Hi @adeelq 

Do you have an estimate on how long will it take to fix the issue #216?

Thanks.

**Comment by adeelq** [comment]
Hi @mcspronko Fix for Magento 2 will be ready the end of this month.

**Comment by mcspronko** [comment]
@adeelq thanks for the response. Looking forward to the fix.

**Comment by mcspronko** [comment]
Hi @adeelq 

What release version should we expect to have the fix?

Thanks.

**Comment by adeelq** [comment]
Hi @mcspronko This will be in next release due to be released next week.
