### ISSUE TITLE
Incorrect dependency in class Dotdigitalgroup\Email\Helper\Data

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#23]
So the class included in Helper/Data.php is already used in parent helper class $this->_remoteAddress

\Magento\Framework\HTTP\PhpEnvironment\RemoteAddress

You have to remove DI from constructor and use same $this->_remoteAddress.

**Comment by adeelq** [comment]
good catch @cdiacon i did not see it at all :)
