### ISSUE TITLE
Subscriber status change not functioning properly

### ISSUE THREAD

**Issue by dotZygis** [dotmailer/dotmailer-magento2-extension#234]
This only applies to customers that are subscribers.

- Register an account and subscribe.
- Login to your account.
- Go to newsletter subscriptions and unsubscribe.
- email_contact table will show this contact as **subscribed**, which is not correct.

Do the opposite - account->newsletter subscriptions and subscribe. Contact will be **unsubscribed**.

Looks like the functionality is working the opposite way.

**Comment by dotZygis** [comment]
After further investigation: newsletter_subscriber_save_after returns outdated subscriber status.

**Comment by adeelq** [comment]
This one seems to be a core bug

**Comment by adeelq** [comment]
newsletter_subscriber_save_after event behaving like newsletter_subscriber_save_before event
