### ISSUE TITLE
Subscriber guest is not removed from email_contact

### ISSUE THREAD

**Issue by cdiacon** [dotmailer/dotmailer-magento2-extension#242]
Subscriber guest is not removed from email_contact when is deleted as subscriber.

**Comment by TrGlen** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #242: Subscriber guest is not removed from email_contact](https://trello.com/c/x6eUtQgY/670-issue-242-subscriber-guest-is-not-removed-from-email-contact)
