### ISSUE TITLE
Extension upgrade after 2.1.6 version have stopped sending emails from magento

### ISSUE THREAD

**Issue by anup4ranium** [dotmailer/dotmailer-magento2-extension#261]
We have installed Magento2 dotamiler extension with version 2.1.6 in our store having Magento ver. 2.1.2 .

Store was working fine when 2.1.6 version extension is present (with disabled state). However when we upgraded this extension through composer to 2.1.7 or later versions, its causing issue & email stopped sending from the system . Issue is present even if extension is present in disabled state.

When I reverted it to 2.1.6 version, emails are again working fine.

**Comment by cdiacon** [comment]
Hi @anup4ranium can you provide any logs and the exact connector version that will help you with this issue?

**Comment by anup4ranium** [comment]
Hi @cdiacon  ,  @dotZygis  have already fixed this issue for us & have all information about it. Its just that fix is not added to repository here. Could you please check with @dotZygis for this ?

**Comment by cdiacon** [comment]
@anup4ranium great thanks

**Comment by cdiacon** [comment]
rewrite conflict for this file Magento\Framework\Mail\Transport
