### ISSUE TITLE
Subscriber Sync Cron Failed

### ISSUE THREAD

**Issue by leandrosunrise** [dotmailer/dotmailer-magento2-extension#287]
<img width="594" alt="capture" src="https://cloud.githubusercontent.com/assets/19354168/26176488/2cbe859c-3b0b-11e7-96d4-00b03225e140.PNG">

When there are no custom attributes added to a default customer data mapping the will fail ddg_automation_customer_subscriber_guest_sync with message Invalid argument supplied foreach() Dotdigitalgroup\Email\Model\Apiconnector\Contact  on line 252 

``` if ($connectorCustomer) {
                foreach ($customAttributes as $data) {
                    $attribute = $data['attribute'];
                    $value = $customer->getData($attribute);
                    $connectorCustomer->setData($value);
                }
            } 
```
fix: 
```if ($connectorCustomer) {
                if (!empty( $customAttributes )) {
                    foreach ($customAttributes as $data) {
                        $attribute = $data['attribute'];
                        $value = $customer->getData($attribute);
                        $connectorCustomer->setData($value);
                    }
                }

            }
```

**Comment by cdiacon** [comment]
This was fixed and it's on testing branch related to the new serialization/unserialization
