### ISSUE TITLE
Insecure field use on system config

### ISSUE THREAD

**Issue by leandrosunrise** [dotmailer/dotmailer-magento2-extension#301]
For password is better to use \Magento\Framework\Data\Form\Element\Obscure instead of simple password html field as you guys have used on the configuration area. One can just look at the source code and copy  the credentials. 
<img width="698" alt="capture" src="https://cloud.githubusercontent.com/assets/19354168/26361456/e14f2b28-3f8f-11e7-9270-cc2f5bcc1bd6.PNG">

**Comment by cdiacon** [comment]
Hi @leandrosunrise ,

Thanks for sending this over, we are aware of it and once we'll have the compatibility with the crypt and other cryptography issues used on various php versions we'll have this updated.
