### ISSUE TITLE
Default branch?

### ISSUE THREAD

**Issue by zack6849** [dotmailer/dotmailer-magento2-extension#324]
Hi There!

Your installation instructions isay to download a zip from github, but your default branch is 'testing' not master, meaning whenever we download we get the testing build.

Is this deliberate?

I just want to ensure that the testing branch is what you intend for customers to download by default.

**Comment by cdiacon** [comment]
Hi @zack6849 you should switch to master if you want to use zip file

**Comment by zack6849** [comment]
Well yes, i'm aware of that, but don't you think that shouldn't be required?

Users, by default, will be sent the testing branch when they download a zip.

Do you want users to have to go out of their way to avoid accidentally downloading code from your testing branch?

Your documentation links github as the best source for releases, since you're not using releases, the only way to get a release is to download a zip, which will, by default, download the testing branch

Meaning customers are prone to accidentally download your testing branch, do you not see this as concerning?

**Comment by piotrkwiecinski** [comment]
@zack6849 there releases in this repository: 
https://github.com/dotmailer/dotmailer-magento2-extension/releases

Not sure if your setup allows for it, but I reckon composer is best way to handle module updates.

**Comment by zack6849** [comment]
Huh, maybe i just missed the releases button the first time around, i withdraw my complaint, haha, sorry for the trouble, it just struck me as really strange.

**Comment by cdiacon** [comment]
@zack6849 glad you solved your problem and understand that ftp is not the best way to install the extenstion but we have updated the docs thanks to @piotrkwiecinski https://support.dotmailer.com/hc/en-gb/articles/216121988-Installation#mag2viaftp
