### ISSUE TITLE
EDC not reachable for Abandoned Cart

### ISSUE THREAD

**Issue by anuradha** [dotmailer/dotmailer-magento2-extension#335]
Hi There, 
When access the abandoned cart email link it returns an exception. This is because the connector M2(2.2.1) Abandoned Cart EDC not reachable. It seems there is a bug in the code.

Path: dotmailer-magento2-extension/Controller/Response.php (line #87)

` elseif ($flag && !strpos($output, '<table') !== false) {
`
should be 
` elseif ($flag && !strpos($output, '<table') === false) {
`

Can you please check this?

**Comment by cdiacon** [comment]
Hi @anuradha, actually that change will have no effect to the dynamic content as it not used in 2.2.1

but you want to check the this docs first https://support.dotmailer.com/hc/en-gb/articles/216282318-Security-settings

**Comment by anuradha** [comment]
Hi @cdiacon  I have checked the document you sent and already whitelisted the Dotmailer Ips.
BTW, if the change will have no effect to the dynamic content as it not used in 2.2.1, still it's in the code. 

Is there any idea why EDC is not reachable? why we cannot see the EDC when browsing the abandoned cart link?

**Comment by cdiacon** [comment]
@anuradha it's better if you check the logs for more information, if you need help you can create a support ticket.
