### ISSUE TITLE
Guest export only collects customer_email and website

### ISSUE THREAD

**Issue by piotrkwiecinski** [dotmailer/dotmailer-magento2-extension#406]
Module version: 2.2.1
Magento 2 version: 2.1.7 CE

We've noticed that guest export from Magento 2 to Dotmailer only sends:
```
mail,emailType,STORE_NAME
``` 

Compared to customer data:
```
CUSTOMER_ID,FIRSTNAME,LASTNAME,DOB,GENDER,WEBSITE_NAME,STORE_NAME,ACCOUNT_CREATED_DATE,LAST_LOGGEDIN_DATE,CUSTOMER_GROUP,REVIEW_COUNT,LAST_REVIEW_DATE,SUBSCRIBER_STATUS,BILLING_ADDRESS_1,BILLING_ADDRESS_2,BILLING_CITY,BILLING_STATE,BILLING_COUNTRY,BILLING_POSTCODE,BILLING_TELEPHONE,DELIVERY_ADDRESS_1,DELIVERY_ADDRESS_2,DELIVERY_CITY,DELIVERY_STATE,DELIVERY_COUNTRY,DELIVERY_POSTCODE,DELIVERY_TELEPHONE,NUMBER_OF_ORDERS,AVERAGE_ORDER_VALUE,TOTAL_SPEND,LAST_ORDER_DATE,LAST_ORDER_ID,TOTAL_REFUND,LAST_INCREMENT_ID,BILLING_COMPANY,DELIVERY_COMPANY,TITLE,MOST_PUR_CATEGORY,MOST_PUR_BRAND,MOST_FREQ_PUR_DAY,MOST_FREQ_PUR_MON,FIRST_CATEGORY_PUR,LAST_CATEGORY_PUR,FIRST_BRAND_PUR,LAST_BRAND_PUR,LAST_QUOTE_ID,Email,EmailType
```

We want to be able to achieve all order information flowing to Dotmailer so that we can build an appropriate single view for all customers.
From here we can segment out into high profile, low profile customers etc and build email campaigns tailored specifically to each segment.

This is currently impossible.

**Comment by cdiacon** [comment]
Hi @piotrkwiecinski 

Thanks for sending this over can you please submit as a feature request on our community forum 

https://support.dotmailer.com/hc/en-gb/community/topics/200432508-Feedback-and-feature-requests
