### ISSUE TITLE
Not Guest = Guest

### ISSUE THREAD

**Issue by bsstaveley** [dotmailer/dotmailer-magento2-extension#42]
Currently when an order is found that has been placed by a guest the contact is added to the email_contact table as Not Guest. However they should be added as Guest. The mistake is only a label typo and the guest is actually still being stored as a Guest and is picked up in the guest sync still.

**Comment by cdiacon** [comment]
Should be using filter for option when you have seleted to show not guest (marked as null).

1. Select Guest to filter will show also the label "Guest"
2. Select Not Guest filter "null" values and show no label.

**Comment by cdiacon** [comment]
no need for a new file, update to this : 


```
)->addColumn(
            'is_guest',
            [
                'header' => __('Is Guest'),
                'type' => 'options',
                'index' => 'is_guest',
                'options' => ['1' => 'Guest', 'null' => 'Not Guest'],
                'filter_condition_callback' => [
                    $this,
                    '_filterCallbackContact',
                ],
            ]
```

**Comment by adeelq** [comment]
ahh did not see the filter thanks

**Comment by adeelq** [comment]
@cdiacon using above filter leads to Not Guest label visible in field value

**Comment by cdiacon** [comment]
use this : 'null' => 'Not Guest' as above
