### ISSUE TITLE
Table email_abandoned_cart can't be created

### ISSUE THREAD

**Issue by urosevic** [dotmailer/dotmailer-magento2-extension#483]
Hello,

Related to version 2.3.6 Setup/InstallSchema.php fail to create email_abandoned_cart table because there is an error (also in Setup/UpgradeSchema.php)

**items_ids** field is of type TEXT and have UNSIGNED set to TRUE. Please remove 'unsigned' attribute from line 1650 - check out screenshot https://goo.gl/JKbafw

Thanks,
Aleksandar

**Comment by cdiacon** [comment]
Hi @urosevic 

What is the error you are getting?

**Comment by urosevic** [comment]
@cdiacon

Brice (Ledun) mentioned table email_abandoned_cart to me by mentioning ddg_automation_abandonedcarts cron error:
`'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.email_abandoned_cart' doesn't exist, query was: SELECT COUNT(*) FROM `email_abandoned_cart` AS `main_table` WHERE (`quote_id` = '489702')'`

So when I check DB I found that table does not exists.

Only that table has not added to DB on install/update (started with version 2.3.5 couple days ago). If you try to create table with spec as listed in Setup/InstallSchema.php for that table, you'll get error that SQL query has not valid because of **items_ids** field configuration (UNSIGNED TEXT).

Btw, Brice updated us that you guys already work on fix of install script, so hope it will be good for other/new customers. I add table manually for our project :)

Cheers

**Comment by cdiacon** [comment]
Hi @urosevic, 

Thanks for sending this over, we have done a release today https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v2.3.7 

Let me know if this fixes your issue.

**Comment by urosevic** [comment]
Hi @cdiacon,

Thank you, I upgrade module to v2.3.7, at the moment I see no issues. Thank you for your support,

Aleksandar
