### ISSUE TITLE
Area code not set

### ISSUE THREAD

**Issue by universalathletic** [dotmailer/dotmailer-magento2-extension#484]
When running setup:upgrade after installing the dotmailer module in Magento 2.2 an error is thrown stating "Area code not set: Area code must be set before starting a session." I believe this has something to do with the Setup/InstallData.php file.

**Comment by adeelq** [comment]
@universalathletic Can you please post full error

**Comment by universalathletic** [comment]
There is nothing in the error logs, but below is what it says in the terminal after running setup:upgrade
`Module 'Dotdigitalgroup_Email':
Area code "admin" does not exist`

Magento was is installed already, I was installing dotmailer by itself.
Used composer to install both magento and dotmailer.

**Comment by schleiderb** [comment]
have you tried AREA_GLOBAL or adminhtml?

**Comment by cdiacon** [comment]
closing as cannot replicate.
