### ISSUE TITLE
Infinite spinner in checkout due to adblocker

### ISSUE THREAD

**Issue by robbertstevens** [dotmailer/dotmailer-magento2-extension#500]
I am was using the uBlock adblocker and I got an infinite spinner in the checkout, after some investigation I found out uBlock blocked the trackingCode.js script. After renaming it to something else everything worked fine.

**Comment by robbertstevens** [comment]
@cdiacon can you confirm?

**Comment by cdiacon** [comment]
@robbertstevens yes that is correct, we have fixed this issue and is about to be released.

Thanks.

**Comment by robbertstevens** [comment]
@cdiacon do you have a ETA?

**Comment by cdiacon** [comment]
@robbertstevens it should be released next Wednesday, I'll update you when we'll release it.

**Comment by cdiacon** [comment]
This been fixed and released.
