### ISSUE TITLE
Customer Addressbook Preference 503 error on save

### ISSUE THREAD

**Issue by Thomas-balance** [dotmailer/dotmailer-magento2-extension#502]
Magento Cloud: 2.1.8
dotmailer: latest

Steps to reproduce:

1. Set any address book to public
2. dotmailer-extension config 'Customer Addressbook Preference' set to "Show Addressbooks to 
3. Customer" : "Yes" and select address book/s
4. Set "Show Datafields To Customer?" to "NO"
5. Save
6. Flush Magento cache
7. Login as customer
8. View dashboard > Newsletter
9. Deselect or select an address book
10. Save
11. Page returns a 503 error

Temporary work around:

It seems like the extension  is expecting there to be at least 1 attribute/ Datafield to be displayed here.
When enabling at least 1 attribute/ Datafield then the page can be save successfully.
This is an poor work around as we should be able to just show address book/s.

**Comment by simon-letch** [comment]
Hey @Thomas-balance,

We have raised an internal issue for this and have a fix going through pull request at the moment.

I'll update again when we have released the fix.

Cheers,
Simon

**Comment by cdiacon** [comment]
Hi @Thomas-balance 

This now been fixed on 2.4.5 version.
