### ISSUE TITLE
v2.4.4 Email From Address is empty in Message Object

### ISSUE THREAD

**Issue by dheesbeen** [dotmailer/dotmailer-magento2-extension#503]
Since the version 2.4.4 update the from address is empty. I know which piece of code empties it. Question is, is it correct. We don't use the template functionality (yet). So i should no be emptied i think. 

Please let me know. Other functionalities that uses the email from address don't work anymore.

vendor/dotmailer/dotmailer-magento2-extension/Plugin/MessagePlugin.php

` 
if ($message->getFrom()) {
                $message->clearFrom();
                $message->setFrom($template->getTemplateSenderEmail(), $template->getTemplateSenderName());
}
`

**Comment by cdiacon** [comment]
Hi @dheesbeen ,

Can you clarify the question, you intend to use the feature but you are worried about the from been cleared ?

Thanks,
Calin.

**Comment by cdiacon** [comment]
@dheesbeen
I see the problem now and yes it sets no from data for email and name for default message when the replace don't exist. 

Thanks for sending this will have look to fix this.
