### ISSUE TITLE
[BUG] Checkout redirecting to login/My Account page with dotmailer enabled

### ISSUE THREAD

**Issue by aleksandar-babic** [dotmailer/dotmailer-magento2-extension#509]
## Expected Behavior
Even tho we are not using dotmailer for anything, as Dotmailer is now bundled with Magento (we are on magento 2.2.3) I'm expecting to be able to checkout.

## Current Behavior
When Guest tries to checkout(Proceed to checkout from cart) he gets redirected to login page, When Logged in user tries to checkout(Proceed to checkout from cart) he gets redirected to My Account page.
<br>
When I disable dotmailer extension everything is working as expected.

## Possible Solution
Not sure, but looks like dotmailer is messing up session somehow

## Context (Environment)
Details about our stack:
CentOS 7
Magento 2.2.3 CE (installed with composer)
Nginx 1.12.2
PHP-FPM 7.0.27
Redis used for default and page cache

**Comment by simon-letch** [comment]
Hey @aleksandar-babic,

I'm unable to replicate this issue.

Is it still an issue for you?
