### ISSUE TITLE
Subscriber_updated records filling up email_importer

### ISSUE THREAD

**Issue by bsstaveley** [dotmailer/dotmailer-magento2-extension#51]
On a fresh install into a dotmailer account that already contains a suppression list can sometimes result in the email_importer being filled with subscriber_updated.

Reason being when a contact sync is processed we receive a fault file from dotmailer of contacts who are suppressed. We then update the core newsletter subscriber table that the contact is unsubscribed. As a result we trigger the subscriber save after event, which we observe resulting in a row being added to email_importer. These imports then fail as the contact is suppressed.

The observer on this event needs to be updated to ignore subscriber updates on unsubscribed contacts to stop this from occurring.

**Comment by adeelq** [comment]
I'm not able to replicate this for M2. For M1 yeah sure this exist.
