### ISSUE TITLE
Error when order has no store ID

### ISSUE THREAD

**Issue by barbazul** [dotmailer/dotmailer-magento2-extension#512]
I detected this case when running the M2 Integration Testsuite. 

The issue is with https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Observer/Sales/SaveStatusSmsAutomation.php#L153 when it is called with a `NULL` value it throws an Exception that interrupts the save order process.

Here is the explanation:
When the order has no store ID, `$order->getStoreId()` returns `NULL` so `$storeId` is assinged `NULL`.
Then `$this->storeManager->getStore($storeId)` returns the default store so `$store` gets assigned a valid Store Object
Next, the call to `$appEmulation->startEnvironmentEmulation($storeId);` throws the exception because the original NULL assigned to $storeId is being used, but the algorithm already got a valid Store with its corresponding ID from the storeManager.

To reproduce the error simply install Magento 2 via composer, require this module and run `php bin/magento dev:tests:run integration`

**Comment by adeelq** [comment]
@barbazul Thanks for your contribution. I have reviewed and merged you PR. So closing this issue.
