### ISSUE TITLE
Unable to uninstall Magento due to folder permissions

### ISSUE THREAD

**Issue by billygilbert** [dotmailer/dotmailer-magento2-extension#515]
There are occasions we have seen (but are unable to replicate) where the var/export/email folder is being created in a manner where it can't be deleted.  This is preventing us from being unable to uninstall Magento as the folder can not be cleaned up.  Example permissions are:
```
~/var$ ls -la
...
d-wxr-xr-T  3 web web 4096 Feb  1 08:00 export
~/var/export$ ls -la
...
d-wxr-xr-T 2 web web 4096 Feb  1 08:00 email
```

Presumably the issue started with this change:
https://github.com/dotmailer/dotmailer-magento2-extension/commit/969741ffeeb6c82e0914a73e2142b2395a309171

It seems that changing the line of code from 750 to 0750 should resolve the issue.

**Comment by simon-letch** [comment]
Hey Billy,

I'm going to close this issue as we've merged your pull request.

Thanks,
Simon
