### ISSUE TITLE
Module breaks subject encoding

### ISSUE THREAD

**Issue by xpoback** [dotmailer/dotmailer-magento2-extension#517]
Magento 2.2.5
Module: 2.5.0

**Steps to reproduce:**
1. Create an email template in backend (Marketing->Email Templates) with a character like äüöß in Template Subject

**Expected result:**
1. The characters are displayed correctly
2. It is possible to edit template subject afterwards

**Actual result:**
1. There's a question mark on the place of the character
2. The field is empty on an attempt to edit template

**The _source_ of the problems**: [line one](https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Plugin/TemplatePlugin.php#L90) and [line two](https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Plugin/TemplatePlugin.php#L104)
Also why are you processing template data in the plugin even if the module is not enabled? 
How can you be sure the encoding is not correct? Please, fix.

**Comment by pusachev** [comment]
Same issue 
Magento 2.2.5
Module: 2.5.0

**Comment by adeelq** [comment]
@xpoback Thanks for reporting this. We are working on this in current sprint.

**Comment by xKmz** [comment]
@adeelq Any solution?

**Comment by xpoback** [comment]
@xKmz I'd suggest to disable the module or the plugin. https://github.com/magento/magento2/issues/15620#issuecomment-406292766

**Comment by zaietsv** [comment]
The Dotmailer plugin decodes a gorgeous utf-8 string to a terrible creature by utf8_decode() function http://screenshots.collabstar.com/vza/dd9f6cc8.png It is necessary to rewrite or to disable private function getProcessedTemplatePreviewAndOther() and private function getResultIfArgsEmptyForPreviewAndOther()

**Comment by zhulak** [comment]
I can confirm this issue and would like to see a fix for this as well

**Comment by simon-letch** [comment]
Hey,

We've released the fix for this in v3.0.2 with this commit: 635a62c

Thanks,
Simon

**Comment by zaietsv** [comment]
Magento team just near about of starting to accept this fix https://github.com/magento/magento2/issues/15620#issuecomment-461432405
They are pretty fast developers
