### ISSUE TITLE
Is this running in php7.0.6 version?

### ISSUE THREAD

**Issue by almuete** [dotmailer/dotmailer-magento2-extension#518]
Is this running in php7.0.6 version?

**Comment by simon-letch** [comment]
Hi,

Yes, we support PHP 7.0.6

Thanks,
Simon

**Comment by almuete** [comment]
Hi Simon,

We are using 7.0.6 php version. I found this issue in our magento registration and it popping this error please check screenshot below. When I check the code it pointing to this method:

**private function compresString($templateText): string**

![screen shot 2018-07-26 at 5 51 37 pm](https://user-images.githubusercontent.com/2081976/43372830-7cef6496-93e8-11e8-8ef6-d790dd61f5b0.png)

In addition to my investigation return type is supported in php 7.1 version
![screen shot 2018-07-30 at 11 11 54 am](https://user-images.githubusercontent.com/2081976/43372933-85b2919c-93e9-11e8-8b44-365337a323b3.png)
