### ISSUE TITLE
$dynamicStyle nameColor and fontSize return NULL in basket.phtml

### ISSUE THREAD

**Issue by a-mendoza** [dotmailer/dotmailer-magento2-extension#519]
Hi,

This 2 variables return NULL in basket.phtml template

`$block->escapeHtml($dynamicStyle['nameColor'])`
`$block->escapeHtml($dynamicStyle['fontSize'])`

In src/store/vendor/dotmailer/dotmailer-magento2-extension/Helper/Config.php

This 2 lines must be changed (lines 124 and 125 aprox.)

`const XML_PATH_CONNECTOR_DYNAMIC_NAME_COLOR = 'connector_configuration/dynamic_content_style/name_color';`
by :
`const XML_PATH_CONNECTOR_DYNAMIC_NAME_COLOR = 'connector_configuration/dynamic_content_style/font_color';`

and

`const XML_PATH_CONNECTOR_DYNAMIC_NAME_FONT_SIZE = 'connector_configuration/dynamic_content_style/name_font_size';`
by :
`const XML_PATH_CONNECTOR_DYNAMIC_NAME_FONT_SIZE = 'connector_configuration/dynamic_content_style/font_size'`

**Comment by simon-letch** [comment]
Hey @a-mendoza,

I've added this to our sprint board and the fix is currently under review.

I'll update again once released to our master branch.

Thanks,
Simon

**Comment by simon-letch** [comment]
This has been fixed.
