### ISSUE TITLE
Issue with Redirect to Cart in Cart Abandonment Email

### ISSUE THREAD

**Issue by dewayneholden** [dotmailer/dotmailer-magento2-extension#532]
As a registered customer, when trying to access your cart from an abandoned cart email, after being directed to the login page, rather than going to your cart, you are instead redirected to the customer account page. Please note that this is not related to the configuration option, "Redirect Customer to Account Dashboard after Logging in."

### Preconditions

1. Magento Commerce 2.2.6
2. PHP 7.1.22
3. MySQL Ver 14.14
4. Dotmailer (any version)

### Steps to reproduce

1. Ensure that the configuration option "Redirect Customer to Account Dashboard after Logging in" is set to "No"
1. Trigger an abandoned cart email from a logged-in user's quote.
	* Login as a user
	* Add items to your cart
	* Important: Logout of the customer account
2. After you receive an abandoned cart email, click on the link in the email: "Take Me To My Basket"
	* The link that is generates looks like the following: http://domain.dev/connector/email/getbasket/quote_id/123456/
3. Login as the same customer when prompted.

### Expected result

* I will be taken to the cart.

### Actual result

* I am taken to the customer account page.

### Additional Details

* This is due to https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Controller/Email/Getbasket.php#L130
* The method call ought to be set to setBeforeAuthUrl() instead of the setAfterAuthUrl() method.
* This is because of how \Magento\Customer\Model\Account\Redirect::prepareRedirectUrl() works.
* In that core method, since the before\_auth\_url is not set, it sets $url to the same value as $baseUrl. Then, the rest of the code never accesses the after\_auth\_url value.

**Comment by sta1r** [comment]
@dewayneholden Thank you for this bug report - good spot.

We've committed a fix per your suggestion, which will be merged to `master` in an upcoming release.
