### ISSUE TITLE
Email templates squash images that are not square

### ISSUE THREAD

**Issue by CHallski** [dotmailer/dotmailer-magento2-extension#535]
The following template calls do not utilize Magento's keepAspectRatio and keepFrame options to gracefully resize images, resulting in non-square images being squashed:

- https://github.com/dotmailer/dotmailer-magento2-extension/blob/07baaa6fe8a0c0c357e14abfabc5c15c0eb522b3/view/frontend/templates/email/basket.phtml#L198-L202
- https://github.com/dotmailer/dotmailer-magento2-extension/blob/07baaa6fe8a0c0c357e14abfabc5c15c0eb522b3/view/frontend/templates/email/review.phtml#L93
- https://github.com/dotmailer/dotmailer-magento2-extension/blob/07baaa6fe8a0c0c357e14abfabc5c15c0eb522b3/view/frontend/templates/email/wishlist.phtml#L98
- https://github.com/dotmailer/dotmailer-magento2-extension/blob/07baaa6fe8a0c0c357e14abfabc5c15c0eb522b3/view/frontend/templates/product/list.phtml#L102

This can be overridden with individual template files, but it would be nice if the base block were updated to default to keeping the original aspect ratio (and frame for centering): template handling method for _basket.phtml_ below:

`<?php $_image = $_imagehelper->init($_product, 'product_small_image')->constrainOnly(false)->keepAspectRatio(true)->keepFrame(true)->resize(135); ?>
<img class="photo image" src="<?= $_image->getUrl(); ?>" width="<?= $_image->getWidth() ?>" height="<?= $_image->getHeight() ?>" alt="<?= $_image->getLabel() ?>" />
`

**Comment by sta1r** [comment]
Hello @CHallski. We find that with the Magento Luma demo theme, default behaviour for the small product image (135 x 135px) is for e.g. portrait images to be resized proportionally, with a white frame added. `keepAspectRatio` and `keepFrame` both default to true. 

_Large image_
![mh01-gray_main_3-1](https://user-images.githubusercontent.com/77671/61210792-7f08eb00-a6f5-11e9-8d10-2b0db707d7d2.jpg)

_Resized small image_
![mh01-gray_main_3](https://user-images.githubusercontent.com/77671/61210801-85976280-a6f5-11e9-9fa3-0712bf1ed0a0.jpg)

Perhaps there is something else in your setup that is squashing the images?

**Comment by CHallski** [comment]
Most likely:
```
<image id="product_small_image" type="small_image">
     <width>135</width>
     <height>135</height>
     <frame>false</frame>
</image>
```
in the theme view.xml for front-end display in general, which you're defaulting off of for the emails as well.

This may just be a case where we need to *not* have the frames on the front end due to CSS drop shadows, but we want them in the email to handle older clients and it's something we'll have to continue customizing if the out-of-the-box functionality is as intended.

**Comment by sta1r** [comment]
Indeed, we're just going off the vanilla Luma configuration for `product_small_image`: https://github.com/magento/magento2/blob/2.3-develop/app/design/frontend/Magento/luma/etc/view.xml#L113-L116. Theming for different contexts is left up to you guys to wrestle with! Good luck with it.
