### ISSUE TITLE
Will changes in Dotmailer API reflected in Magento?

### ISSUE THREAD

**Issue by ahasAmp** [dotmailer/dotmailer-magento2-extension#538]
Is there any way to reflect the changes in Dotmailer API to Magento?

If I use the API to subscribe, unsubscribe or delete a customer, will these changes synced to Magneto?

**Comment by sta1r** [comment]
Hi @ahasAmp 

On the whole, no - the sync is one-way from Magento to Engagement Cloud. The main exception to this rule is in handling suppressed contacts.

During every sync of Magento subscribers, we fetch a list of recently suppressed contacts from Engagement Cloud, and use this to ensure that email addresses unsubscribed via the API don't get resubscribed with older data from Magento.
