### ISSUE TITLE
Magento 2.3.1 Enterprise (error in vendor/dotmailer/dotmailer-magento2-extension-enterprise/etc/adminhtml/system.xml)

### ISSUE THREAD

**Issue by ionutturdean** [dotmailer/dotmailer-magento2-extension#539]
Hello, 
The following file :
vendor/dotmailer/dotmailer-magento2-extension-enterprise/etc/adminhtml/system.xml at line 5
has an incorect tab declartion:
`<tab>ddg_automation</tab>`
This is causing magento to crash
`"0":"Notice: Undefined index: id in \/var\/www\/iredeem\/master\/vendor\/magento\/module-config\/Model\/Config\/Structure\/Element\/Iterator.php on line 63","1":"<pre>#1 Magento\\Config\\Model\\Config\\Structure\\Element\\Iterator->setElements() called at [vendor\/magento\/module-config\/Model\/Config\/Structure.php:146]\n#2 Magento\\Config\\Model\\Config\\Structure->getTabs() called at [generated\/code\/Magento\/Config\/Model\/Config\/Structure\/Interceptor.php:24]\n#3 Magento\\Config\\Model\\Config\\Structure\\Interceptor->getTabs() called at [vendor\/magento\/module-config\/Model\/Config\/Structure.php:209]\n#4 Magento\\Config\\Model\\Config\\Structure->getFirstSection() called at [generated\/code\/Magento\/Config\/Model\/Config\/Structure\/Interceptor.php:76]\n#5 `

**Comment by sta1r** [comment]
@ionutturdean Thanks for this. In fact this has already been raised as an issue against our dotmailer-magento2-extension-enterprise repository, please see https://github.com/dotmailer/dotmailer-magento2-extension-enterprise/issues/13. Closing this one.
