### ISSUE TITLE
TransportPlugin send exception: Zend\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided

### ISSUE THREAD

**Issue by kerlama** [dotmailer/dotmailer-magento2-extension#540]
Hi,

today I upgraded magento from 2.2.7 to 2.2.8 and transactional emails stopped working.

This is the error I got in connector.log

TransportPlugin send exception: Zend\Mail\Transport\Smtp transport expects either a Sender or at least one From address in the Message; none provided

**Comment by simon-letch** [comment]
Hey @kerlama,

Could you confirm which version of the dotdigital extension you are using?

**Comment by kerlama** [comment]
Hi @simon-letch 

it is 2.7.1

**Comment by kerlama** [comment]
Hi @simon-letch 

any updates, were you able to reproduce the issue ?

**Comment by sta1r** [comment]
@kerlama I've not been able to replicate testing 2.2.8 with version 2.7.1 of our connector. I've tested using our transactional SMTP with and without templates stored down from Engagement Cloud. I didn't see the error in connector.log. 

It might be best to log a ticket with our support team (https://dotdigital.com/services/support/), providing as much additional info as possible about your setup. 

Thanks.
