### ISSUE TITLE
Doc link does not work

### ISSUE THREAD

**Issue by aleksandrosadchiy** [dotmailer/dotmailer-magento2-extension#541]
https://support.dotdigital.com/hc/en-gb/categories/360000368744-dotmailer-for-Magento-2

**Comment by TrGlen** [comment]
Hi Aleks - Thanks for reporting. 
The correct link is now https://support.dotdigital.com/hc/en-gb/sections/360000722900-Engagement-Cloud-for-Magento-2 .
Can I ask where you found the reference to this broken link?

Thanks,
Tristan
