### ISSUE TITLE
Preference checkboxes have invalid ID attribute if 'public name' has more than one word

### ISSUE THREAD

**Issue by BDierks** [dotmailer/dotmailer-magento2-extension#543]
We are attempting to style our Newsletter Subscriptions page in Magento 2, but we have encountered a bug. We are utilizing Marketing Preferences to manage our subscribers' frequency preferences. 
When attempting to read in the category and preferences, the values being passed from dotdigital to create the labels and id attributes are the public names. The integration uses the public name as the input label, but also as the input “id” attribute. If we attempt to use a public name that contains spaces, the resulting code is invalid since the [HTML5 specification](https://www.w3.org/TR/html5/dom.html#element-attrdef-global-id) prohibits spaces.

For example, we have a marketing preference as follows: 
category private name='Frequency'
category public name='How often would you like to receive marketing email?'
preference private name='Daily' 
preference public name='Send me everything!'

Since the public name is being passed from dotdigital, we're seeing the following for the preference:
id="Send me everything!_606" value="605,606"

![screenshot-3](https://user-images.githubusercontent.com/2778640/57025224-8b0c0300-6c04-11e9-954b-b5840acfcbe9.png)

Magento 2.3.1
dotdigital Engagement Cloud (formerly dotmailer) for Magento 2 - 3.1.1
dotmailer for Magento 2 Enterprise - V1.0.3

**Comment by adeelq** [comment]
Thanks @BDierks for reporting this. We have added this to current sprint. Will update you when released.

**Comment by sta1r** [comment]
Hi @BDierks, fix released in https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v3.2.4.
