### ISSUE TITLE
Product Catalog reimport never triggered after import via import-export

### ISSUE THREAD

**Issue by marieevekroy** [dotmailer/dotmailer-magento2-extension#544]
**Actual behavior**
When a product is saved, there is an observer on `catalog_product_save_after` event that reimport catalog product in Dotmailer.

**Problematic behavior**
When importing multiple products with magento-catalog-import-export module however, this event is never dispatched and therefore, the reimport for all those products in Dotmailer is never made. The catalog in Dotmailer is then offsync with actual data in Magento.

**Desired behavior**
There should be an observer in Dotmailer module on the event `catalog_product_import_bunch_save_after` that would resync the data for the product ids in the imported bunch.

Using the latest version of the module.

**Comment by sta1r** [comment]
@marieevekroy Thank you for raising this. Per your suggestion we've shipped a fix [here](https://github.com/dotmailer/dotmailer-magento2-extension/commit/ac4b6d26cda2c4b7e7b7a9e1009d5469fa9578f3), which is due for release in v3.2.2 in the next few days.
