### ISSUE TITLE
CustomerPlugin definition - buggy code

### ISSUE THREAD

**Issue by nileshti** [dotmailer/dotmailer-magento2-extension#546]
This logic in CustomerPlugin class is buggy one, How one can write Plugin for Protected function sendNewAccountEmail? This code will never execute with Magento 2.3.1.

<type name="Magento\Customer\Model\Customer">
         <plugin name="ddg_customer_sendNewAccountEmail_disabler" type="Dotdigitalgroup\Email\Plugin\CustomerPlugin" sortOrder="1" disabled="false"/>
</type>

**Comment by simon-letch** [comment]
Hey @nileshti,

Unless i'm missing something, that function is public in Magento 2.3.1: https://github.com/magento/magento2/blob/2.3.1/app/code/Magento/Customer/Model/Customer.php#L763

**Comment by simon-letch** [comment]
I'm going to close this issue, but please re-open if you can share more info.
