### ISSUE TITLE
No link to products in crosssell, upsell and related products blocks

### ISSUE THREAD

**Issue by adamj88** [dotmailer/dotmailer-magento2-extension#547]
There appears to be a problem in the the `product/list.phtml` template where by links to the product are returned as empty, so we see `href=""` where there should be a product URL.

The problem looks to be with this line of code in the template returning as empty: https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/view/frontend/templates/product/list.phtml#L80

The only reference to this method in the module is in the `Block/Recommended/Bestsellers.php` file here: https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Block/Recommended/Bestsellers.php#L112

Looking in the layout XML files this is not the block used for Upsells (for example) https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/view/frontend/layout/connector_product_related.xml#L7

Would you be open to a PR to fix this?

**Comment by simon-letch** [comment]
Changes are in develop branch: https://github.com/dotmailer/dotmailer-magento2-extension/commit/ac52a3c69faa585a489366140c82bfc6cb84c520

This will make it to master as part of our next release.
