### ISSUE TITLE
Problem with magento 2 messages 

### ISSUE THREAD

**Issue by Januszpl** [dotmailer/dotmailer-magento2-extension#550]
There are issues with displaying messages. For example: confirmation message after subscribing to newsletter.

Related to:
https://github.com/magento/magento2/issues/12390

Similar fixes were implement in mailchimp extension:
https://github.com/mailchimp/mc-magento2/issues/112

One possible solution: changing ajax call from post to get in emailCapture.js
Perhaps there is other/better solution you could implement in your module. This seems to be a quick fix.

**Comment by sta1r** [comment]
Hi @Januszpl thank you for raising this. I've seen your related issues, but please could you outline specific steps and conditions to replicate the error in our module?

**Comment by sta1r** [comment]
Closing this one. On investigation we don't think this issue affects how our `emailCapture` tool functions at checkout. Feel free to re-open if you have steps to replicate.
