### ISSUE TITLE
Abandoned carts: Guest campaign should be configurable on store view level

### ISSUE THREAD

**Issue by mcardin-absolunet** [dotmailer/dotmailer-magento2-extension#552]
https://github.com/dotmailer/dotmailer-magento2-extension/blob/30252dc257b8b412af9fb6b878b1f9830f8c2405/etc/adminhtml/system.xml#L549

Shouldn't the campaign to be sent to guests also be configurable on Store level?
`
<field id="campaign_1" translate="label" sortOrder="40" type="select" showInDefault="1"
                       showInWebsite="1" showInStore="1">
`

Let's take the example "Website A' with two store views: French and English

The campaign used for the "Website A" would be "DDG French campaign". Using the Website level configuration, guests from the store view English would therefore receive the DDG French campaign even if the "DDG English campaign" exists.

**Comment by sta1r** [comment]
@mcardin-absolunet Thank you for this. We will push a fix to activate guest AC campaign configuration at store level. I'll confirm once this is released.

**Comment by sertlab** [comment]
@mcardin-absolunet Fixed in [3.4.1](https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v3.4.1). Thank you
