### ISSUE TITLE
Order sync cron failing Call to a member function getTypeId() on null 

### ISSUE THREAD

**Issue by gingerben** [dotmailer/dotmailer-magento2-extension#555]
Cron is failing due to wrong attribute type been called

should be product_type . not type_id

Run Dotdigitalgroup\Email\Model\Cron::orderSync PHP Fatal error:  Uncaught Error: Call to a member function getTypeId() on null in /data/webroot/mag2.paulsmith.com/20200116_110133/vendor/dotmailer/dotmailer-magento2-extension/Model/Connector/Order.php:333
Stack trace:
#0 /data/webroot/mag2.paulsmith.com/20200116_110133/vendor/dotmailer/dotmailer-magento2-extension/Model/Connector/Order.php(246): Dotdigitalgroup\Email\Model\Connector\Order->processOrderItems(Object(Magento\Sales\Model\Order\Interceptor), '0')
#1 /data/webroot/mag2.paulsmith.com/20200116_110133/vendor/dotmailer/dotmailer-magento2-extension/Model/Sync/Order.php(373): Dotdigitalgroup\Email\Model\Connector\Order->setOrderData(Object(Magento\Sales\Model\Order\Interceptor))
#2 /data/webroot/mag2.paulsmith.com/20200116_110133/vendor/dotmailer/dotmailer-magento2-extension/Model/Sync/Order.php(302): Dotdigitalgroup\Email\Model\Sync\Order->mapOrderData(Object(Dotdigitalgroup\Email\Model\ResourceModel\Order\Collection\Interceptor), Object(Dotdigitalgroup\Email\Model\Order), Array)
#3 /data/webroot/mag2.paulsmith.com/20 in /data/webroot/mag2.paulsmith.com/20200116_110133/vendor/dotmailer/dotmailer-magento2-extension/Model/Connector/Order.php on line 333

product {"item_id":"3002798","order_id":"1034553","parent_item_id":null,"quote_item_id":"3411810","store_id":"1","created_at":"2019-08-03 10:08:47","updated_at":"2020-01-13 13:26:58","product_id":"61164","product_type":"configurable","product_options":"{\"info_buyRequest\":{\"uenc\":\"aHR0cHM6Ly93d3cucGF1bHNtaXRoLmNvbS91ay9tZW4tcy1ibGFjay1jYWxmLWxlYXRoZXItbG9tYXgtb3hmb3JkLXNob2Vz\",\"product\":\"61164\",\"selected_configurable_option\":\"61156\",\"related_product\":\"\",\"item\":\"61164\",\"super_attribute\":{\"250\":\"785\"},\"qty\":\"1\"},\"attributes_info\":[{\"label\":\"Size\",\"value\":\"6 (EU 40)\",\"option_id\":250,\"option_value\":\"785\"}],\"simple_name\":\"MENS SHOE LOMAX BLACK\",\"simple_sku\":\"M1S-LOM05-APAR-79-6\",\"product_calculations\":1,\"shipment_type\":0,\"giftcard_lifetime\":null,\"giftcard_is_redeemable\":0,\"giftcard_email_template\":null,\"giftcard_type\":null}","weight":"1.0000","is_virtual":"0","sku":"M1S-LOM05-APAR-79-6","name":"Men's Black Calf Leather 'Lomax' Oxford Shoes ","description":null,"applied_rule_ids":null,"additional_data":null,"is_qty_decimal":"0","no_discount":"0","qty_backordered":null,"qty_canceled":"0.0000","qty_invoiced":"1.0000","qty_ordered":"1.0000","qty_refunded":"1.0000","qty_shipped":"0.0000","base_cost":null,"price":"152.5000","base_price":"152.5000","original_price":"365.0000","base_original_price":"365.0000","tax_percent":"20.0000","tax_amount":"30.5000","base_tax_amount":"30.5000","tax_invoiced":"30.5000","base_tax_invoiced":"30.5000","discount_percent":"0.0000","discount_amount":"0.0000","base_discount_amount":"0.0000","discount_invoiced":"0.0000","base_discount_invoiced":"0.0000","amount_refunded":"152.5000","base_amount_refunded":"152.5000","row_total":"152.5000","base_row_total":"152.5000","row_invoiced":"152.5000","base_row_invoiced":"152.5000","row_weight":"1.0000","base_tax_before_discount":null,"tax_before_discount":null,"ext_order_item_id":null,"locked_do_invoice":null,"locked_do_ship":null,"price_incl_tax":"183.0000","base_price_incl_tax":"183.0000","row_total_incl_tax":"183.0000","base_row_total_incl_tax":"183.0000","discount_tax_compensation_amount":"0.0000","base_discount_tax_compensation_amount":"0.0000","discount_tax_compensation_invoiced":"0.0000","base_discount_tax_compensation_invoiced":"0.0000","discount_tax_compensation_refunded":"0.0000","base_discount_tax_compensation_refunded":"0.0000","tax_canceled":null,"discount_tax_compensation_canceled":null,"tax_refunded":"30.5000","base_tax_refunded":"30.5000","discount_refunded":"0.0000","base_discount_refunded":"0.0000","free_shipping":"0","qty_returned":"0.0000","weee_tax_applied":"[]","weee_tax_applied_amount":null,"weee_tax_applied_row_amount":null,"weee_tax_disposition":null,"weee_tax_row_disposition":null,"base_weee_tax_applied_amount":null,"base_weee_tax_applied_row_amnt":null,"base_weee_tax_disposition":null,"base_weee_tax_row_disposition":null,"gift_message_id":null,"gift_message_available":"0","giftregistry_item_id":null,"gw_id":null,"gw_base_price":null,"gw_price":null,"gw_base_tax_amount":null,"gw_tax_amount":null,"gw_base_price_invoiced":null,"gw_price_invoiced":null,"gw_base_tax_amount_invoiced":null,"gw_tax_amount_invoiced":null,"gw_base_price_refunded":null,"gw_price_refunded":null,"gw_base_tax_amount_refunded":null,"gw_tax_amount_refunded":null,"event_id":null,"giftcard_email_sent":null,"svs_processed":null,"giftcard_delivery_date":null,"farfetch_order_line_id":null,"farfetch_order_line_status_code":null,"subscription_orders_processed":null,"erp_data":"{\"sku\":\"M1S-LOM05-APAR\",\"matrix\":{\"code1\":\"79\",\"code2\":\"6\",\"code3\":null,\"code4\":null}}","erp_qty_alloc":"1","erp_qty_unalloc":"0","in_stock_shops":null,"has_children":true,"product_option":"object(Magento\\Catalog\\Model\\ProductOption) {}"}
[Order.php.zip](https://github.com/dotmailer/dotmailer-magento2-extension/files/4085898/Order.php.zip)

**Comment by benathomeofchampions** [comment]
@gingerben Thanks - we have put out a patch release to address this issue!
