### ISSUE TITLE
Error on setup:di:compile on Magento 2.3.4

### ISSUE THREAD

**Issue by tanolalano** [dotmailer/dotmailer-magento2-extension#562]
Hi all,
after upgrade from magento 2.3.3 to 2.3.4 and after:

- update composer

- run setup:upgrade

On setup:di:compile command 
 I get this error 

`Repositories code generation... 1/7 [====>-----------------------]  14% 1 sec 40.0 MiBPHP Fatal error:  Interface 'Dotdigitalgroup\Email\Block\Adminhtml\EngagementCloudEmbedInterface' not found in /htdocs/vendor/dotmailer/dotmailer-magento2-extension-chat/Block/Adminhtml/StudioChatWidget.php on line 12`

But if I open StudioChatWidget.php on line 12 I found Interface
![Schermata 2020-05-01 alle 09 41 58](https://user-images.githubusercontent.com/4384863/80790780-05f95800-8b90-11ea-940a-138c2cae8689.png)

Thank you for supporting

**Comment by sta1r** [comment]
Hi @tanolalano potentially you are using an older version of Email than the one bundled with Magento 2.3.4? Did you previously require a specific version of `Dotdigitalgroup_Email`?

**Comment by sta1r** [comment]
Closing, feel free to re-open if you have further problems.
