### ISSUE TITLE
m2.3.5-p1 Dicompile error dotmailer

### ISSUE THREAD

**Issue by alexbk31** [dotmailer/dotmailer-magento2-extension#563]
after upgrading to m2.3.5-p1 ive updated all my extentions and there all working fine but now dotmailer is causing an decompile error 

Compilation was started.
Interception cache generation... 6/8 [===========>---]  75% 3 mins 470.0 MiBErrors during compilation:
        Dotdigitalgroup\Email\Model\Apiconnector\EngagementCloudAddressBookApi
                Incompatible argument type: Required type: \Dotdigitalgroup\Email\Logger\Logger. Actual type: \Dotdigitalgroup\Email\Helper\File; File:
/home/healthcb/public_html/vendor/dotmailer/dotmailer-magento2-extension/Model/Apiconnector/EngagementCloudAddressBookApi.php

Total Errors Count: 1

In Log.php line 92:

  Error during compilation

**Comment by sta1r** [comment]
@alexbk31 do you have an existing alias for this module in your composer.json file? 

2.3.5-p1 comes bundled with 4.4.0 of this extension, and the file `Model/Apiconnector/EngagementCloudAddressBookApi.php` does not exist in this version:

https://github.com/dotmailer/dotmailer-magento2-extension/tree/v4.4.0/Model/Apiconnector

**Comment by alexbk31** [comment]
Thanks for your response I did think it shouldn't be there when I upgraded its the only file with an old date on

im not sure  if we had an existing alias for this module in composer.json we was on m2.3.3 we didn't have a dotmail digital account until now

![dotmail](https://user-images.githubusercontent.com/51369531/81194752-eeb5d280-8fb4-11ea-9c27-034b7fca4d95.png)

**Comment by alexbk31** [comment]
sorted thanks I just removed all the files that were left behind now all working thanks

**Comment by alexbk31** [comment]
do have the file tree for 4.4.0 the one on the link is 3.6.0

**Comment by sta1r** [comment]
@alexbk31 the v4.4.0 file tree is the right one i.e. as per the 2.3.5-p1 bundle, but well spotted the version is still 4.3.6. I will fix this.
