### ISSUE TITLE
\Dotdigitalgroup\Email\Model\Sync\Importer\ImporterProgressHandler::_processContactImportReportFaults() suppressed contacts resubscription

### ISSUE THREAD

**Issue by naliva** [dotmailer/dotmailer-magento2-extension#565]
in  version 4.5.4 according to change log following has been changed:
- We fixed an issue with contacts being resubscribed even if their last_subscribed_at value was null.

I'm concerned that you are checking "last_subscribed_at" in this method instead of checking additionally email_contact.suppressed. From the situation we've faced it has resubscribed the record which had email_contact.suppressed=1 and email_contact.last_subscribed_at=null. Your change in 4.5.4 version handles this situation but you are referring to last_subscribed_at filtering instead of email_contact.suppressed so i believe this filtering is indirect and still there might happen situations where suppressed contacts have last_subscribed_at!=null and they are resubscribed (i never faced such situation but it might occur)

**Comment by sta1r** [comment]
@naliva Thanks for raising this. 

From our most recent testing we're confident that the `NULL` check on `email_contact.last_subscribed_at` is sufficient to catch genuine resubscribes. However we're going to look again in light of this issue and I'll update here in due course. 

In the meantime, if you are able to replicate contacts with recent `last_subscribed_at` dates, who are also `email_contact.suppressed` = 1, that would be useful.

**Comment by sta1r** [comment]
@naliva We've released an improvement to our [handling of resubscribes from the contact import report](03b3cc63670509fdbb6db66f99973a043fda4e0a). Thanks again for raising this.
