### ISSUE TITLE
Dotdigitalgroup\Email\Model\Product::getProductIdsBySkuInBunch missing product Ids

### ISSUE THREAD

**Issue by darrenf-fisheye** [dotmailer/dotmailer-magento2-extension#567]
Dotdigitalgroup\Email\Model\Product::getProductIdsBySkuInBunch is returning the array_keys of the collection and not the product id's as expected by Dotdigitalgroup\Email\Model\Catalog::processBatch

Replacing the following in Dotdigitalgroup\Email\Model\Product::getProductIdsBySkuInBunch fixes the issue:
	 	$productIds = array_keys($productItems);

with:
        $productIds = [];
        foreach($productItems as $product){
            $productIds[] = $product->getId();
        }

**Comment by sta1r** [comment]
@darrenf-fisheye Hi, and thanks for raising this. We're going to resolve as soon as we can.

**Comment by sta1r** [comment]
Hi again, we've got a fix here: https://github.com/dotmailer/dotmailer-magento2-extension/commit/fc559c86939a677d583279187cb97bab6cce67d4 which we're planning to release to master on October 7.

**Comment by sta1r** [comment]
Now released!
