### ISSUE TITLE
gzuncompress data error when saving design configuration

### ISSUE THREAD

**Issue by paul-gene** [dotmailer/dotmailer-magento2-extension#568]
When trying to set a new Default Theme for the Global scope in Content > Design > Configuration, this error shows:

> Something went wrong while saving this configuration: Warning: gzuncompress(): data error in /var/www/magento2/vendor/dotmailer/dotmailer-magento2-extension/Plugin/TemplatePlugin.php on line 164

This is on Magento 2.3.5-p2, with Dotmailer 4.4.0 (installed with Magento)

**Comment by sta1r** [comment]
@paul-gene Thanks, we'll take a look.

**Comment by sta1r** [comment]
Hi - We were able to replicate the issue, but only by removing the `@` operator on L64. We're using this when checking if the supplied HTML is compressed or not - if there's an error the error should be suppressed and the method returns false. 

What version of PHP are you running please?

**Comment by paul-gene** [comment]
I'm running PHP 7.3.

But, it looks like it was my xdebug settings (scream) that meant the `@` error suppressor was being ignored.

With that said, usage of `@` isn't ideal anyway.

**Comment by sta1r** [comment]
Ah that's actually good intel re xdebug. I was seeing the error in a different context and wondering why. 

Yes we'd much prefer a try catch but `gzuncompress` doesn't throw an exception. 

Previous to using `@gzuncompress` we had:
```
if (substr($string, 0, 1) == 'e' && substr_count($string, ' ') == 0) {
    return true;
}

return false;
```

but this was returning false positives in some cases. 

If you know of a better way we'd happily check it out! 👍

**Comment by sta1r** [comment]
I think that's a workaround for cases where you are ingesting compressed strings that you didn't originally compress yourself - we'd be confident that any compressed template strings would have been compressed by us initially. 

We know for sure that campaigns can exceed 64kb in size (mysql's limit for TEXT columns), so we do need some solution for compressing the HTML.
