### ISSUE TITLE
Type Error Occured when creating object: Dotdigitalgroup\Email\Model\Catalog\UrlFinder

### ISSUE THREAD

**Issue by waseemshahri** [dotmailer/dotmailer-magento2-extension#571]
Type Error Occured when creating object:
Dotdigitalgroup\Email\Model\Catalog\UrlFinder  before place order

**Comment by sta1r** [comment]
@waseemshahri Hi there, please can you give us more detail about this error? e.g. a full stack trace, your current Magento version and connector version? With a bit more info we can take a look.
