### ISSUE TITLE
Commands not found

### ISSUE THREAD

**Issue by deiserh** [dotmailer/dotmailer-magento2-extension#572]
**Reproduction**
1. Install Magento
2. Execute bin/magento

**Expected Result**
- There is a dotdigital section with four commands

**Actual Result**
- No dotdigital commands are shown

**Comment by sta1r** [comment]
@deiserh Hi, is this an issue with 2.4.2? Or an older version. Can't seem to replicate here.

**Comment by sta1r** [comment]
Hi, we'll update our code as you suggest and let you know when it's on `develop`.

**Comment by sta1r** [comment]
@deiserh this is complete now and on our master branch.
