### ISSUE TITLE
Di compile failed

### ISSUE THREAD

**Issue by haiacom** [dotmailer/dotmailer-magento2-extension#575]
Hi ,

I am using Magento 2.3.2(PHP 7.2), I upgraded the extension to 4.13.1 and got di:compile failed:
PHP Parse error:  syntax error, unexpected ')' in vendor/dotmailer/dotmailer-magento2-extension/Model/Newsletter/Unsubscriber.php on line 178

I temporarily created a patch to fix it but better to have fix from Dotmailer

Regards,
Hai.

**Comment by sertlab** [comment]
Hi thanks for raising the issue.
We fixed this now on 4.13.2
