### ISSUE TITLE
Trying to get property 'status' of non-object (running ddg_automation_abandonedcarts cron)

### ISSUE THREAD

**Issue by NoDiskInDriveA** [dotmailer/dotmailer-magento2-extension#577]
- Magento `magento/product-enterprise-edition:2.3.6-p1`
- Dotmailer `dotmailer/dotmailer-magento2-extension:4.4.1-p1`

As far as I'm aware, this still apllies to the current master

This happens in `Model\AbandonedCart\PendingContactUpdater::checkStatusForPendingContactsInternal()`:

```
foreach ($collection as $item) {
    $websiteId = $this->helper->storeManager->getStore($item->getStoreId())->getWebsiteId();
    $contact   = $this->helper->getOrCreateContact($item->getEmail(), $websiteId);
    if (isset($contact->id) && $contact->status !== Automation::CONTACT_STATUS_PENDING) {
        $idsToUpdateStatus[] = $item->getId();
    } elseif (($item->getCreatedAt() < $expiryDate) &&
              $contact->status === Automation::CONTACT_STATUS_PENDING
    ) {
        $idsToExpire[] = $item->getId();
    } else {
        $idsToUpdateDate[] = $item->getId();
    }
}
```

`Dotdigitalgroup\Email\Helper\Data::getOrCreateContact()` will return false in case the response says the contact is not subscribed:
```
if (isset($response->status) && $response->status !== 'Subscribed') {
    $contact->setEmailImported(1);
    $contact->setSuppressed(1);
    $this->saveContact($contact);
    return false;
}
```

So `$contact->status === Automation::CONTACT_STATUS_PENDING` will trigger an error if the item is expired.

Removing the `return false;` fixes my specific use case, but I'm not sure about other implications this might have.

**Comment by sta1r** [comment]
@NoDiskInDriveA thanks for this, you're right of course. We'll patch it and report back.

**Comment by NoDiskInDriveA** [comment]
Thanks for your quick reply - yeah that was the decision we made, not to patch your code but remove the two offending contacts from the DB, since the method is used in multiple places and we're not very familiar with the API side of this 😬.

We'll be watching this issue and backport any patch that eventually comes up. Thanks again!

**Comment by sta1r** [comment]
@NoDiskInDriveA Our [4.13.5 release](https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v4.13.5) should resolve your pending contact issues. Thanks again for raising.

**Comment by NoDiskInDriveA** [comment]
Thanks!
