### ISSUE TITLE
Previously public functions changed to private, breaking Plugins

### ISSUE THREAD

**Issue by CsSatter** [dotmailer/dotmailer-magento2-extension#583]
Although PHP standards may dictate certain class methods to be private, Magento's Interceptor implementation requires methods to be public for things like Plugins to work correctly. Example being previously made Plugin on `\Dotdigitalgroup\Email\Model\Connector\Order::_getOrderItemOptions`.

**Comment by sertlab** [comment]
Hi thanks for sharing the issue.
In our next release we're planning to make `Order::_getOrderItemOptions` function public again.

**Comment by CsSatter** [comment]
Excellent, thanks for the update (and my apologies for the delayed response).
