### ISSUE TITLE
upgrade Magento 2.4.5 then this extension will work?

### ISSUE THREAD

**Issue by BrightDhiru** [dotmailer/dotmailer-magento2-extension#592]
@sta1r  @pavelshulga  Magento version 2.3.5 and I had installed this extension.
When I will upgrade Magento 2.4.5 then this will work proper or need to upgrade from your end.?

**Comment by pvpcookie** [comment]
HI @BrightDhiru 

Yes it should work 😄.

As mentioned in #591 
> Our extension currently supports magento version 2.4.5 if you use the latest release [ 4.19.1](https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v4.19.1) you should not have a problem when upgrading your magento to 2.4.5
