### ISSUE TITLE
Extension doesn't support PHP 8.1.

### ISSUE THREAD

**Issue by kenitchiu** [dotmailer/dotmailer-magento2-extension#593]
Hi,

We have a Magento v2.4.5 instance running on PHP 8.1 environment, we tried to install this extension and composer showed it doesn't support php 8.1.
Do you guys have any plan to add the support of PHP 8.1?

**Comment by sta1r** [comment]
@kenitchiu It should work fine, what's the exact error you get?

**Comment by kenitchiu** [comment]
I believe the error is due to there is a PHP version limitation ^8.0 in the composer.json file, so the composer doesn't allow the extension be installed in 8.1 environment.

**Comment by sta1r** [comment]
The constraint `^7.2||^8.0` is equivalent to '>=7.2 <8.0' OR '>=8.0 < 9.0'.

**Comment by vacla** [comment]
I can confirm this, https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/Model/Consent.php#L205 , it is possible that "$customerConsentText" can return null, causing it to fail.

**Comment by sta1r** [comment]
@vacla Thanks, we're aware of that one. In general we _do_ support 8.1, we did a pretty thorough [sweep for possible errors a few months ago](https://github.com/dotmailer/dotmailer-magento2-extension/commit/9bef461f5df12e0d7566aee88f4c95dc26a41007). The odd issue does still crop up but we're repairing those as quickly as we can.

**Comment by sta1r** [comment]
@vacla a quick fix for that particular issue is to enter text into the text boxes in Dotdigital > Configuration > Consent. But we'll be fixing this in 4.19.4, released next week.
