### ISSUE TITLE
Magento 2 Exception Stores - Configuration - Dotmailer - Abandoned Carts

### ISSUE THREAD

**Issue by ThomasNegeli** [dotmailer/dotmailer-magento2-extension#6]
Registry key "campaigns" already exists
#0 /var/www/releases/20160407162119/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Model/Config/Source/Carts/Campaigns.php(36): Magento\Framework\Registry->register('campaigns', Array)
#1 /var/www/releases/20160407162119/htdocs/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(443): Dotdigitalgroup\Email\Model\Config\Source\Carts\Campaigns->toOptionArray(false)
#2 /var/www/releases/20160407162119/htdocs/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(361): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel(Object(Dotdigitalgroup\Email\Model\Config\Source\Carts\Campaigns))
#3 /var/www/shared/var/generation/Magento/Config/Model/Config/Structure/Element/Field/Interceptor.php(310): Magento\Config\Model\Config\Structure\Element\Field->getOptions()
#4 /var/www/releases/20160407162119/htdocs/vendor/magento/module-config/Block/System/Config/Form.php(379): Magento\Config\Model\Config\Structure\Element\Field\Interceptor->getOptions()
#5 /var/www/releases/20160407162119/htdocs/vendor/magento/module-config/Block/System/Config/Form.php(284): Magento\Config\Block\System\Config\Form->_initElement(Object(Magento\Config\Model\Config\Structure\Element\Field\Interceptor), Object(Magento\Framework\Data\Form\Element\Fieldset), 'abandoned_carts...', '', '')
#6 /var/www/releases/20160407162119/htdocs/vendor/magento/module-config/Block/System/Config/Form.php(224): Magento\Config\Block\System\Config\Form->initFields(Object(Magento\Framework\Data\Form\Element\Fieldset), Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section))
#7 /var/www/releases/20160407162119/htdocs/vendor/magento/module-config/Block/System/Config/Form.php(170): Magento\Config\Block\System\Config\Form->_initGroup(Object(Magento\Config\Model\Config\Structure\Element\Group), Object(Magento\Config\Model\Config\Structure\Element\Section), Object(Magento\Framework\Data\Form))
#8 /var/www/releases/20160407162119/htdocs/vendor/magento/module-config/Block/System/Config/Form.php(458): Magento\Config\Block\System\Config\Form->initForm()
#9 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(656): Magento\Config\Block\System\Config\Form->_beforeToHtml()
#10 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#11 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system\\config\\f...')
#12 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system\\config\\f...')
#13 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system\\config\\f...')
#14 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system\\config\\f...', true)
#15 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(497): Magento\Framework\View\Layout\Interceptor->renderElement('system\\config\\f...', true)
#16 /var/www/releases/20160407162119/htdocs/vendor/magento/module-config/view/adminhtml/templates/system/config/edit.phtml(22): Magento\Framework\View\Element\AbstractBlock->getChildHtml('form')
#17 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/TemplateEngine/Php.php(59): include('/var/www/releas...')
#18 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Element/Template.php(255): Magento\Framework\View\TemplateEngine\Php->render(Object(Magento\Config\Block\System\Config\Edit), '/var/www/releas...', Array)
#19 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Element/Template.php(279): Magento\Framework\View\Element\Template->fetchView('/var/www/releas...')
#20 /var/www/releases/20160407162119/htdocs/vendor/magento/module-backend/Block/Template.php(104): Magento\Framework\View\Element\Template->_toHtml()
#21 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Element/AbstractBlock.php(657): Magento\Backend\Block\Template->_toHtml()
#22 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(542): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(518): Magento\Framework\View\Layout->_renderBlock('system.config.e...')
#24 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('system.config.e...')
#25 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('system.config.e...')
#26 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('system.config.e...', true)
#27 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('system.config.e...')
#28 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('content')
#29 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('content')
#30 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('content')
#31 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('content', true)
#32 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('content')
#33 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('admin.scope.col...')
#34 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('admin.scope.col...')
#35 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('admin.scope.col...')
#36 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('admin.scope.col...', true)
#37 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('admin.scope.col...')
#38 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('main.col')
#39 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('main.col')
#40 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('main.col')
#41 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('main.col', true)
#42 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('main.col')
#43 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.main.conta...')
#44 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.main.conta...')
#45 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.main.conta...')
#46 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.main.conta...', true)
#47 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.main.conta...')
#48 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.content')
#49 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.content')
#50 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.content')
#51 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.content', true)
#52 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.content')
#53 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('page.wrapper')
#54 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#55 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('page.wrapper')
#56 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('page.wrapper', true)
#57 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('page.wrapper')
#58 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('backend.page')
#59 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('backend.page')
#60 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('backend.page')
#61 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('backend.page', true)
#62 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(569): Magento\Framework\View\Layout\Interceptor->renderElement('backend.page')
#63 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(520): Magento\Framework\View\Layout->_renderContainer('root')
#64 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(206): Magento\Framework\View\Layout->renderNonCachedElement('root')
#65 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(472): Magento\Framework\View\Layout\Interceptor->renderNonCachedElement('root')
#66 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(193): Magento\Framework\View\Layout->renderElement('root', true)
#67 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Layout.php(938): Magento\Framework\View\Layout\Interceptor->renderElement('root')
#68 /var/www/shared/var/generation/Magento/Framework/View/Layout/Interceptor.php(492): Magento\Framework\View\Layout->getOutput()
#69 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Result/Page.php(241): Magento\Framework\View\Layout\Interceptor->getOutput()
#70 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/View/Result/Layout.php(162): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#71 /var/www/shared/var/generation/Magento/Backend/Model/View/Result/Page/Interceptor.php(193): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#72 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/App/Http.php(119): Magento\Backend\Model\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#73 /var/www/releases/20160407162119/htdocs/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch()
#74 /var/www/releases/20160407162119/htdocs/pub/index.php(37): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http))
#75 {main}

**Comment by ThomasNegeli** [comment]
Nearly the same error occures on Automation (programs) and Configuration Tab.
Please check your registry key inserts!!!

**Comment by cdiacon** [comment]
Thanks @ThomasNegeli can you try to remove the cache also this folder var/generation var/cache/ and see if the issue persists.

What versions you are using?

**Comment by ThomasNegeli** [comment]
Latest M2 and Dotmailer Extensions

**Comment by ThomasNegeli** [comment]
Caches were cleared from the beginning.

**Comment by cdiacon** [comment]
@ThomasNegeli Just having the cache disabled is not enough, can you please remove these folders 

var/di
var/generation
var/cache

if you have for example "campaigns" the registry as a key it will never try again so please do this and let me know if you still have this issue.

**Comment by bpoiss** [comment]
In developr mode it is working when I clear the di folder, but in production mode after deleting the di folder and running magento setup:di:compile the following errors occur during compilation:

Errors during compilation:
	Dotdigitalgroup\Email\Block\Recommended\Mostviewed
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Recommended\Mostviewed in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Mostviewed.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Recommended\Wishlistproducts
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Recommended\Wishlistproducts in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Wishlistproducts.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Recommended\Recentlyviewed
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Recommended\Recentlyviewed in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Recentlyviewed.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Recommended\Quoteproducts
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Recommended\Quoteproducts in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Quoteproducts.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Recommended\Push
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Recommended\Push in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Push.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Recommended\Product
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Recommended\Product in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Product.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Product
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Product in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Product.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Basket
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Basket in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Basket.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Feefo
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Feefo in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Feefo.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Coupon
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Coupon in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Coupon.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Order
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Order in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Order.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
	Dotdigitalgroup\Email\Block\Wishlist
		Incorrect dependency in class Dotdigitalgroup\Email\Block\Wishlist in /var/www/releases/20160413082508/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Wishlist.php
\Magento\Framework\App\Config\ScopeConfigInterface already exists in context object
Total Errors Count: 12

**Comment by cdiacon** [comment]
@bpoiss are you using composer, can you post here the version number?

**Comment by bpoiss** [comment]
@cdiacon yes, magento version is 2.0.4 and dotmailer 1.1.4

**Comment by cdiacon** [comment]
@bpoiss can you please update to 1.1.5 and let me know if this works for you?

**Comment by bpoiss** [comment]
Now I get another error during compilation:

PHP Fatal error:  Cannot use Magento\Catalog\Model\Product as Product because the name is already in use in /var/www/releases/20160413122924/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Mostviewed.php on line 5

**Comment by bpoiss** [comment]
@cdiacon Updating to 1.1.5 solved the problem for me

**Comment by cdiacon** [comment]
great, @bpoiss can you click around Automation (programs) and Configuration Tabs and see if you get campaigns in select options?

**Comment by bpoiss** [comment]
I already checked this and it's working, but during the di:compile command I get the following error: Fatal error:  Cannot use Magento\Catalog\Model\Product as Product because the name is already in use in /var/www/releases/20160413132101/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Mostviewed.php on line 5
Even with this error everything is working, but I think this will become a problem in some other place. Should I create a new issue for this one?

**Comment by bpoiss** [comment]
When I go to Configuration - Dotmailer - Automation I get a blank page. Also while di:compile I get the following error: 

> Fatal error: Cannot use Magento\Catalog\Model\Product as Product because the name is already in use in /var/www/releases/20160413132101/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Block/Recommended/Mostviewed.php on line 5

**Comment by cdiacon** [comment]
yes please, also can you post the command you run setup:di:compile or setup:di:compile-multi-tenant

**Comment by bpoiss** [comment]
I run `php bin/magento setup:di:compile` in the magento2 root directory. All caches and generation folder are cleared, di folder is deleted. File permissions are correct, even with 777 i get the same error.

**Comment by cdiacon** [comment]
ok, what kind of blank page anything in log files?

can update composer to use the "dev-master" instead of "1.1.5" and run compiler again?

**Comment by bpoiss** [comment]
This is the html output:

```
<html><head></head><body><form action="https://xxx/admin/system_config/save/section/connector_automation/key/abbdb098259278d2e4245a3fee8c0c677f380ca4cb6a8379dafde2c3c84a206e/" method="post" id="config-edit-form" enctype="multipart/form-data">
    <div><input name="form_key" type="hidden" value="Fog69bKGlpRRYWtu"></div>
    <div class="accordion">
        </div></form></body></html>
```

Magento logs are empty, nginx error log says:

```
2016/04/13 15:43:14 [error] 6832#0: *2552 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getText() on string in /var/www/releases/20160413124542/htdocs/vendor/dotmailer/dotmailer-magento2-extension/Model/Config/Configuration/Orderstatus.php:34
Stack trace:
#0 /var/www/releases/20160413124542/htdocs/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(443): Dotdigitalgroup\Email\Model\Config\Configuration\Orderstatus->toOptionArray(false)
#1 /var/www/releases/20160413124542/htdocs/vendor/magento/module-config/Model/Config/Structure/Element/Field.php(361): Magento\Config\Model\Config\Structure\Element\Field->_getOptionsFromSourceModel(Object(Dotdigitalgroup\Email\Model\Config\Configuration\Orderstatus))
#2 /var/www/releases/20160413124542/htdocs/vendor/magento/module-config/Block/System/Config/Form.php(379): Magento\Config\Model\Config\Structure\Element\Field->getOptions()
#3 /var/www/releases/20160413124542/htdocs/vendor/magento/module-config/Block/System/Config/Form.php(284): Magento\Config\Block\System\" while reading response header from upstream, client: 10.1.0.11, server: , request: "GET /xxx/admin/system_config/edit/section/connector_automation/key/1273bc19d5651d7832a67e7a01e961b187cb78302202d8e2a129392e0091abea/ HTTP/1.0", upstream: "fastcgi://unix:/var/run/php-fpm.socket:", host: "xxx"
```

**Comment by cdiacon** [comment]
should be fine now if you use "dev-master"
let me know and I'll bump the version number.

**Comment by cdiacon** [comment]
@bpoiss

**Comment by bpoiss** [comment]
@cdiacon It's fine with dev-master now
