### ISSUE TITLE
Di Compilation breaks Magento 2.4.3 PHP 7.2 

### ISSUE THREAD

**Issue by nishpatel** [dotmailer/dotmailer-magento2-extension#602]
Updated to version 4.2.0 of Magento 2 extension. 

Di Compilation fails two files which are causing this issue:

Dotdigitalgroup\Email\Observer\Adminhtml\ResetCustomerImport
Line 39 trailing comma

Dotdigitalgroup\Email\Model\Sync\Automation\AutomationProcessor
Line 134 catch hasn't a variable.

**Comment by sta1r** [comment]
@nishpatel Thanks for flagging, we'll sort this out.

**Comment by sta1r** [comment]
I'm presuming you mean: Magento 2.3.4 (since 2.4.3 doesn't run on 7.2) and 4.20.0?

**Comment by dbashyal** [comment]
Same issue here. Sent an email to the support team.

**Comment by TomJ1588** [comment]
Can confirm, dotmailer v4.20 or os-package 1.6.0 breaks compile with the mentioned error on Magento 2.4.3-p3

**Comment by sta1r** [comment]
Hi folks, we're going to patch this for you ASAP. 4.20.1 coming tomorrow I hope.

**Comment by sta1r** [comment]
4.20.1 is released: https://github.com/dotmailer/dotmailer-magento2-extension/releases/tag/v4.20.1

You can get this from Packagist now. A new metapackage (1.6.1) will be available on the marketplace later today.
