### ISSUE TITLE
Is this compatible Hyva Theme?

### ISSUE THREAD

**Issue by Anantkprajapati** [dotmailer/dotmailer-magento2-extension#604]
Hello Team,

Is there any version to compatible with Hyva Theme?

**Comment by sta1r** [comment]
Hi - Compatibility modules are available for Email and Chat in the Hyvä Gitlab:

https://gitlab.hyva.io/hyva-themes/hyva-compat?filter=dotdigital

These have been written by members of the Hyvä community.

**Comment by Anantkprajapati** [comment]
Thank @sta1r for update. closing this comment.
