### ISSUE TITLE
Problem with composer install after module was added to packagist

### ISSUE THREAD

**Issue by smiroshnyk** [dotmailer/dotmailer-magento2-extension#616]
Hello.

**Problem Description:**

You added your module to packagist - [https://packagist.org/packages/dotdigital/dotdigital-magento2-extension](https://packagist.org/packages/dotdigital/dotdigital-magento2-extension)

Also, you didn't delete it from the Magneto marketplace.

I have an exception when I try to run composer install:

<img width="700" alt="image" src="https://github.com/dotmailer/dotmailer-magento2-extension/assets/20116324/47de8c00-b602-437c-8f23-215640e3595c">

**Steps to reproduce:**
1. Try to run composer install without composer.lock file when you have https://repo.magento.com/ in repositories

**Comment by rajesh-xcube** [comment]
I am also getting issue since morning. Waiting for fix

**Comment by sta1r** [comment]
Sorry about this - we tagged 4.22.0 too early, before it was accepted by the marketplace. We got rejected for some tiny things at marketplace submission, so withdrew the tag on Github. I thought it would automatically remove it from Packagist but it was still there, so I have now manually removed it there too. 

4.22.0 will be re-tagged as soon as we're live on the marketplace.

**Comment by sta1r** [comment]
Note: if you get this:
```
Higher matching version 4.21.6 of dotdigital/dotdigital-magento2-extension was found in public repository packagist.org
than 4.21.5 in private https://repo.magento.com/. Public package might've been taken over by a malicious entity,
please investigate and update package requirement to match the version from the private repository
```
please try:
```
composer require dotdigital/dotdigital-magento2-os-package --no-plugins
```
