### ISSUE TITLE
Class \"Dotdigitalgroup\\Email\\Block\\Adminhtml\\Logviewer\" not found 

### ISSUE THREAD

**Issue by anduel1419** [dotmailer/dotmailer-magento2-extension#617]
Class file name is LogViewer but inside file is used Logviewer
<?php

namespace Dotdigitalgroup\Email\Block\Adminhtml;

/**
 * Log viewer block
 *
 * @api
 */
class Logviewer extends \Magento\Backend\Block\Widget\Container
{

    /**
     * @var string
     */
    public $_template = 'log.phtml';

    /**
     * @var \Dotdigitalgroup\Email\Helper\File
     */
    public $file;

    /**
     * /**
     * Logviewer constructor.
     *
     * @param \Magento\Backend\Block\Widget\Context $context
     * @param \Dotdigitalgroup\Email\Helper\File $file
     * @param array $data
     */
    public function __construct(
        \Magento\Backend\Block\Widget\Context $context,
        \Dotdigitalgroup\Email\Helper\File $file,
        array $data = []
    ) {
        $this->file = $file;
        parent::__construct($context, $data);
    }

    /**
     * @return void
     */
    public function _construct()
    {
        $this->_controller = 'adminhtml_logviewer';
        $this->_headerText = __('Log Viewer');
        parent::_construct();
    }

    /**
     * Get log file content
     *
     * @return string
     */
    public function getLogFileContent()
    {
        return nl2br($this->_escaper->escapeHtml($this->file->getLogFileContent()));
    }

    /**
     * @return string
     */
    public function getAjaxUrl()
    {
        return $this->getUrl('dotdigitalgroup_email/connector/ajaxlogcontent');
    }
}

**Comment by pvpcookie** [comment]
Hi @anduel1419 

Thanks for raising this, we will get back to soonest.

**Comment by pvpcookie** [comment]
Hi @anduel1419 

Who did you come across the error?
is this breaking your current Magento instance?

**Comment by anduel1419** [comment]
It's not causing any issue in general; it's just can't access logs in backend. I am Magento Developer and after I updated to the latest version, I saw this issue trying to access the logs
________________________________

**Comment by anduel1419** [comment]
Just rename the class file from LogViewer to Logviewer or rename the class inside or anywhere that is used.

**Comment by pvpcookie** [comment]
Hi @anduel1419 ,

Apologies for the frustration. We have addressed the issue and included a fix that will be part of the next release. Thank you for bringing this to our attention. I will get back to you with the release date for the updated version.
