### ISSUE TITLE
Abandoned Browse: Grouped Product Prices Displayed as Zero

### ISSUE THREAD

**Issue by amjadm61** [dotmailer/dotmailer-magento2-extension#624]
**Current Environment:**
Adobe Commerce Version: 2.4.5-p2
PHP Version: 8.1
DotDigital for Magento: 4.23.6

**Issue Description:**
While navigating grouped products to test the abandoned browse program, an issue arises where the displayed price appears as zero instead of the expected Magento default format of 'As low as: $xx' on the abandoned browse email.

**Steps to Reproduce:**
Access any grouped product to trigger the abandoned browse program.
Observe the pricing display for the grouped products on the abandoned browse email.
[https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/view/frontend/web/js/webBehaviorTracking.js#L61](url)

**Expected Result:**
The pricing display for grouped products on the email should adhere to the Magento default format and showcase the correct pricing information instead of displaying zero.

**Comment by sta1r** [comment]
@amjadm61 Thank you, we're going to investigate this week.

**Comment by sta1r** [comment]
The logic governing what bits of `product_data` to post with the update is here: https://github.com/dotmailer/dotmailer-magento2-extension/blob/master/view/frontend/web/js/webBehaviorTracking.js#L51-L70.

We probably need to provide access to 
```
productData.price_info.minimal_price
productData.price_info.extension_attributes.tax_adjustments.minimal_price
```

(or `minimal_regular_price`) for grouped product types.

**Comment by amjadm61** [comment]
In the Dotdigital email easy editor, do we have an option to retrieve the product type and use it with a conditional operator? If so, from Magento, we can pass the lowest price of the grouped simple products. Then, in the Dotdigital email, we can display it as follows: If the product type is 'grouped,' show the price with a label 'As low as: $lowestPrice'

**Comment by sta1r** [comment]
No, the product type isn't exposed in the insight data. And in any case, `regular_price` might be 0 for all grouped products, so you don't currently have access to a valid price. Good to know your use case though. Will come back on this thread.

**Comment by amjadm61** [comment]
@sta1r Any update on this?

**Comment by sta1r** [comment]
Yes, we'll be fixing this in our release next week. We're _either_ going to include `type` in the schema _or_ show you how to potentially use catalog insight data to fetch the type using the product id from web insight schema.

**Comment by sta1r** [comment]
@amjadm61 A fix for this will be included in our newest metapackage from the Adobe marketplace: https://commercemarketplace.adobe.com/dotdigital-dotdigital-magento2-os-package.html, in the next day or so [v3.1.0].  

As you'll see from the merge commit, we are now including `product_type` in the schema for web insights.
