### ISSUE TITLE
Error on updating to 4.25.1 with Magento 2.4.7

### ISSUE THREAD

**Issue by parthppwd** [dotmailer/dotmailer-magento2-extension#627]
Hello,

Store running on Magento 2.4.7 

I am updating dot-digital extension to latest version to support transition from `Zend` to `Laminas` 

While installing facing below issues, as in version `4.25.1` there is require composer of `psr/log` to version `^1.0` here - https://github.com/dotmailer/dotmailer-magento2-extension/blob/v4.25.1/composer.json#L58

But Magento has updated 2.4.7 to only user `"psr/log": "^2 || ^3"` - https://github.com/magento/magento2/blob/2.4.7/composer.json#L84

So, while doing `composer update` getting following error

```
- You can only install one version of a package, so only one of these can be installed: psr/log[1.0.0, ..., 1.1.4, 2.0.0, 3.0.0].
- Conclusion: don't install one of psr/log[3.0.0], dotdigital/dotdigital-magento2-extension[4.25.1] (conflict analysis result)
- Conclusion: install psr/log 3.0.0 (conflict analysis result)
```

and if I just install dot-digital with `composer require dotdigital/dotdigital-magento2-os-package` then it install older version 2.0.4 , and while compiling getting below zend error

```
There is an error in /var/www/html/vendor/dotdigital/dotdigital-magento2-extension/Model/Events/Response/StreamedResponse.php at line: 7
Class "Zend\Http\Response" not found#0 /var/www/html/vendor/composer/ClassLoader.php(576): include()
```

`4.22.0` is the version where `zend` issue is fixed with `laminas` while also added requirement of `"psr/log": "^1.0"`

**Comment by parthppwd** [comment]
@sta1r 
Possible to check quickly? we are blocked in upgrading the site to 2.4.7 due to this issue

**Comment by sta1r** [comment]
Hi there - yes this was escalated to us via our support team also. We have a [fix for this already](https://github.com/dotmailer/dotmailer-magento2-extension/blob/develop/composer.json#L58) which we are looking to release either late this week or first thing next week.

**Comment by parthaccorin** [comment]
Thank you @sta1r for quick response,

Just want to make sure similar update will be there for all other dotmailer magento2 extension too right?

like https://github.com/dotmailer/dotmailer-magento2-extension-sms/ & https://github.com/dotmailer/dotmailer-magento2-extension-b2b/

**Comment by sta1r** [comment]
Great spot, thank you! Yes we'll update all affected modules.

**Comment by sta1r** [comment]
To confirm v3.3.2 of our metapackage is now available on the marketplace: https://commercemarketplace.adobe.com/dotdigital-dotdigital-magento2-os-package.html

B2B is also released here: https://github.com/dotmailer/dotmailer-magento2-extension-b2b/releases/tag/v1.8.2

Thanks again for flagging this.
