### ISSUE TITLE
Error on CRON after saving consent on customer account

### ISSUE THREAD

**Issue by VictorSoaresRedstage** [dotmailer/dotmailer-magento2-extension#629]
Hello,

We have a store running on Adobe Commerce on PREM - 2.4.5-p7, with 2 websites, 2 stores and 2 store views.
Extension on latest version 4.25.2 with SMS consent enable.

If we save "General Subscription" on /connector/customer/index with checkbox checked, a value is saved on the table "email_contact_consent" with column "consent_text" equals NULL, throwing an error on the cron:

dotdigital.DEBUG: Error exporting consent data for contact: [vsoares@redstage.com]["Dotdigital\\Exception\\ValidationException: Dotdigital\\V3\\Models\\Contact\\ConsentRecord::setText(): Argument #1 ($text) must be of type string, null given, called in .../magento/vendor/dotdigital/dotdigital-php/src/V3/Models/AbstractSingletonModel.php on line 77 in .../vendor/dotdigital/dotdigital-php/src/V3/Models/AbstractSingletonModel.php:61

![image](https://github.com/dotmailer/dotmailer-magento2-extension/assets/117660000/478d60bf-9732-4b84-808f-288613e050ac)

**Comment by sta1r** [comment]
Thanks - we need to make this more robust, but all you need to do is set consent text Marketing Consent > SMS > SMS marketing consent text.

**Comment by VictorSoaresRedstage** [comment]
> Thanks - we need to make this more robust, but all you need to do is set consent text Marketing Consent > SMS > SMS marketing consent text.

Thank you!

**Comment by bartoszkubicki** [comment]
This is reproducible on version 3.5.2 and definitely shouldn't be closed. The same situation happens for email consent. This is only a workaround:
![image](https://github.com/user-attachments/assets/c4f6d3ee-824d-4f77-9d81-0ebd7631c019)
Additionally, a dummy consent has to be set for records in table email_contact_conset

**Comment by sta1r** [comment]
@bartoszkubicki Thanks for this. The issue is re-opened and will stay open until we have some better protection added to the UI. i.e. If admins enable consent (for either Email or SMS) they will not be able to save this config before setting consent text.
