### ISSUE TITLE
catalog sync does not take into account disabled stores

### ISSUE THREAD

**Issue by iancassidyweb** [dotmailer/dotmailer-magento2-extension#636]
### Background 
- The catalog sync of the dotdigital connector syncs the catalog for each website & store combination.
- When syncing the catalogs the module does not check the `is_active` flag of the store.
- This means you can end up in a situation of over syncing catalogs that are not required.

### Steps to replicate 

1. Configure magento with sample data and the following store setup:

| Website | Store | Store Status|
| ------ | ------ | ------ |
| United Kingdom | en_gb | enabled |
| Canada | ca_en | enabled |
| Canada | ca_fr | disabled |

2. Enable the DD connector and catalog sync for both websites 

3. Sync the catalogs 

### Current results 
- The en_fr catalog is being synced incorrectly as: whilst the connector is enabled at website level, the store has been disabled.

### Expected results 
- The en_gb catalog should be synced as it's enabled at website and the store is_active.
- The ca_en catalog should be synced as it's enabled at website and the store is_active.
- The en_fr catalog should not be synced as: whilst the connector is enabled at website level, the store has been disabled.

**Comment by pvpcookie** [comment]
Hi @iancassidyweb,

Thank you for this. We will investigate and get back to you as soon as we can :)

**Comment by reenacti** [comment]
hi @pvpcookie Is there any update on this please ? Are you able to provide a tentative date by which we may anticipate a resolution ?

**Comment by pvpcookie** [comment]
Hi @reenacti 

The fix should be live, im gonna close this issue. here is the commit if you interested. [606eee1c0b25b7ec8c31d9402baf249254d7d0fb]

**Comment by sta1r** [comment]
@reenacti @iancassidyweb This finally released after a very long wait for approval at the Commerce Marketplace. Available in v3.7.0 of our metapackage. Thanks for your patience!
