### ISSUE TITLE
Extension breaks setup:upgrade command for other extension

### ISSUE THREAD

**Issue by fetzi** [dotmailer/dotmailer-magento2-extension#7]
Our extension is trying to install a custom indexer and in the State Model your Observer `Dotdigitalgroup\Email\Observer\Customer\RegisterWishlist` which is registered on `model_save_before` is called.

The observer requires a injectable class that needs an area code (frontend, adminhtml) to be set. But that is not the case in `setup:upgrade`. Because of that the upgrade process fails and the shop is unusable.

Can you please rewrite this Observer to use a more specific wishlist event?

Regards,
Johannes

**Comment by fetzi** [comment]
Btw. this observer is decreasing the overall shop performance because the observer gets called on every model save before.

**Comment by cdiacon** [comment]
Hi @fetzi this was already done here https://github.com/dotmailer/dotmailer-magento2-extension/commit/e4e42e2b560ebcb4351ea676a8534ce66e47218e and it looks it's lost during merging.

Thanks.

**Comment by fetzi** [comment]
Hi @cdiacon, when do you plan to fix this again?

Regards Johannes
