### ISSUE TITLE
Wishlist not batching up..throwing error

### ISSUE THREAD

**Issue by adeelq** [dotmailer/dotmailer-magento2-extension#83]
Wishlist sync throws error "Fatal error: Call to a member function setEmail() on null in ...../app/code/Dotdigitalgroup/Email/Model/Sync/Wishlist.php on line 199"

Fatal error: Call to a member function getSize() on null in /Users/adeelqamar/Desktop/Dev_Sites/DM_M2/app/code/Dotdigitalgroup/Email/Model/Sync/Wishlist.php on line 201

**Comment by cdiacon** [comment]
@adeelq 
$_mageWishlistCollection is declared dynamically, needs to be declared.

Also looks it was removed on the second commit.

**Comment by adeelq** [comment]
@cdiacon i think i deleted it by mistake. fixed it in latest commit.

**Comment by cdiacon** [comment]
@adeelq what was the problem with this ?

```
Fatal error: Call to a member function getSize() on null in /Users/adeelqamar/Desktop/Dev_Sites/DM_M2/app/code/Dotdigitalgroup/Email/Model/Sync/Wishlist.php on line 201
```

**Comment by adeelq** [comment]
@cdiacon so line 201 was if ($wishlistItems->getSize()) {

where $wishlistItems = $wishlist->getItemCollection();

$wishlist was item from email_wishlist collection. so the collection should have been from magento wishlist
