### ISSUE TITLE
Registry key "campaigns" already exists

### ISSUE THREAD

**Issue by bpoiss** [dotmailer/dotmailer-magento2-extension#9]
When navigating to configuration - dotmailer - abandoned carts it throws an exception if campaigns is an empty array, cause `if ($savedCampaigns)` evaluates to true, and in the register method of the registry `if (isset($this->_registry[$key]))` evaluates to true which throws the exception.

Please accept my pull request #8

**Comment by cdiacon** [comment]
@bpoiss isset() - will evaluate false and true to always be true if the key exists

http://www.php.net/manual/en/types.comparisons.php

**Comment by bpoiss** [comment]
Yes this is the problem, the key exists but the array is empty... So the expression `if(isset($this->_registry[$key])` is true, this leads to the runtime exception.

```
if (isset($this->_registry[$key])) {
            if ($graceful) {
                return;
            }
            throw new \RuntimeException('Registry key "' . $key . '" already exists');
}
```

**Comment by cdiacon** [comment]
That is how suppose to be as will GET the registry key: 
```
             $savedCampaigns = $this->_registry->registry('campaigns');		
```
 and this : 

```
                $this->_registry->register('campaigns', $campaigns);

```
will try to register

I am sure the problem lies somewhere else .

**Comment by bpoiss** [comment]
Ok I try to explain this issue one last time ^^

$this->_registry->registry('campaigns'); returns an empty array cause  $this->_registry->register('campaigns', $campaigns); registered an empty array

if(array()) is false, so if ($savedCampaigns) is also false. So $this->_registry->register('campaigns', $campaigns); is called which throws the exception cause in the Registry.php it checks with if (isset($this->_registry[$key])), which is true.

I updated your code as in my pull request and now it's working even if there are no campaigns.

**Comment by bpoiss** [comment]
Maybe I should also mention that `$client->getCampaigns()` is the point where the empty array comes from.

**Comment by cdiacon** [comment]
So you have enabled api and no campaings in your account?

I closed the pull-request as isset() is not a good solution.

**Comment by bpoiss** [comment]
Yes `$client->getCampaigns();` returns an empty array. I didn't look into it what happens exactly. For testing you could just change the line  35 to `$campaigns = array();` and you will get the same exception.

**Comment by cdiacon** [comment]
Can you create a testing email campaign in dotmailer account and you should see no error, I am am sure this was a marketing move 😉


Calin.






On Fri, Apr 15, 2016 at 2:01 AM -0700, "Bernhard Poiss" <notifications@github.com> wrote:












Yes $client->getCampaigns(); returns an empty array. I didn't look into it what happens exactly. For testing you could just change the line  35 to $campaigns = array(); and you will get the same exception.

**Comment by bpoiss** [comment]
Yes I know that it is working if there exists at least one campaign ^^
